import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{collection,doc,getDocs,getFirestore,serverTimestamp,updateDoc}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{firebaseConfig}from'./firebase-config.js';
const OWNER_EMAIL='shadrat.almn7@gmail.com';
const css=document.createElement('style');css.textContent=`
.student-toolbar{display:grid;grid-template-columns:minmax(0,2fr) minmax(180px,1fr);gap:10px;margin:16px 0}.student-toolbar input,.student-toolbar select{width:100%;padding:13px 14px;border:1px solid #dbe4f0;border-radius:13px;background:#fff;font:inherit}.student-list{display:grid;gap:10px}.student-row{display:grid;grid-template-columns:54px minmax(0,1.7fr) minmax(180px,1fr);align-items:center;gap:14px;padding:14px 16px;border:1px solid #dbe4f0;border-radius:16px;background:#fff;color:inherit}.student-row.has-unread{border-color:#93c5fd;box-shadow:0 0 0 2px rgba(37,99,235,.06)}.student-avatar{width:48px;height:48px;border-radius:14px;background:#eaf2ff;color:#1d4ed8;display:grid;place-items:center;font-weight:900;font-size:18px}.student-identity{min-width:0}.student-identity b,.student-identity small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.student-identity small{color:#68766f;direction:ltr;text-align:right;margin-top:3px}.student-email,.student-phone{min-width:0;color:#58655f;direction:ltr;text-align:right;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.student-phone{grid-column:2/-1;color:#174f83;font-weight:800}.student-meta{grid-column:1/-1;display:flex;gap:7px;align-items:center;justify-content:flex-end;flex-wrap:wrap}.student-pill{padding:6px 9px;border-radius:999px;background:#f1f5f9;color:#475569;font-size:11px;font-weight:800;white-space:nowrap}.student-unread{padding:6px 10px;border-radius:999px;background:#dc2626;color:#fff;font-size:11px;font-weight:900}.student-open{font-weight:900;color:#1d4ed8;white-space:nowrap;text-decoration:none}.student-status-actions{display:flex;gap:7px;flex-wrap:wrap}.student-status-btn{border:1px solid #d9e2ef;border-radius:999px;padding:7px 10px;background:#fff;color:#26463a;font:inherit;font-size:12px;font-weight:900;cursor:pointer}.student-status-btn.is-current{background:#2563eb;color:#fff;border-color:#2563eb}.student-status-btn:disabled{opacity:.5;cursor:default}.students-empty{padding:22px;border:1px dashed #d8e2ee;border-radius:16px;background:#fff}.students-error{padding:18px;border:1px solid #ecc9c5;border-radius:14px;background:#fff7f6;color:#8f2e27}.status-help{margin:8px 0 14px;padding:12px 14px;border:1px solid #dbe7f3;border-radius:14px;background:#f8fbff;color:#58655f;font-size:13px;line-height:1.8}@media(max-width:760px){.student-toolbar{grid-template-columns:1fr}.student-row{grid-template-columns:48px minmax(0,1fr)}.student-email{grid-column:2/-1}.student-meta{justify-content:flex-start}}
`;document.head.appendChild(css);
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),main=document.querySelector('.admin-main');let users=[],events=[],isOwner=false;
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ms=v=>v?.toMillis?.()||v?.toDate?.()?.getTime?.()||new Date(v||0).getTime()||0;
const timeOf=x=>x.savedAt||x.createdAt||x.updatedAt||null;
const statusLabel=s=>({active:'نشط',restricted:'مقيّد',suspended:'موقوف'}[s]||s||'نشط');
const read=async name=>{try{const s=await getDocs(collection(db,name));return s.docs.map(d=>({id:d.id,...d.data()}))}catch(e){console.warn('[Shadrat users]',name,e);return[]}};
main.innerHTML=`<div class="admin-title"><div><span class="eyebrow">إدارة الطلاب</span><h1>حسابات الطلاب</h1><p class="muted">العلامة الحمراء تعني نشاطًا تشغيليًا جديدًا لم تراجعه بعد. تختفي بعد فتح ملف الطالب.</p></div></div><div class="admin-workspace"><div class="status-help"><b>النشاط الجديد:</b> تسجيل حساب، طلب خدمة، إنشاء/حفظ CV أو Motivation Letter، استخدام أداة، أو رسالة تواصل. لا يعرض هذا القسم محتوى الملفات الخاصة.</div><div class="student-toolbar"><input id="students-search" placeholder="ابحث بالاسم أو @username أو البريد أو الجوال"><select id="students-status"><option value="">كل الحالات</option><option value="active">نشط</option><option value="restricted">مقيّد</option><option value="suspended">موقوف</option></select></div><div id="students-count" class="muted" style="margin-bottom:10px"></div><div class="student-list" id="student-list"></div></div>`;
const listEl=document.querySelector('#student-list'),search=document.querySelector('#students-search'),status=document.querySelector('#students-status'),count=document.querySelector('#students-count');
function unread(u){const seen=ms(u.adminActivityReviewedAt);return events.filter(e=>e.uid===u.uid&&e.at>seen).length}
function filtered(){const q=search.value.trim().toLowerCase().replace(/^@/,'');return users.filter(u=>(u.role||'student')==='student'&&(!status.value||u.accountStatus===status.value)&&(!q||[u.fullName,u.username,u.email,u.phoneE164,u.phoneLast4].some(v=>String(v||'').toLowerCase().includes(q))))}
async function setStatus(uid,next,button){if(!isOwner)return;button.disabled=true;const previous=button.textContent;button.textContent='جارٍ...';try{await updateDoc(doc(db,'users',uid),{accountStatus:next,updatedAt:serverTimestamp(),lastAdminEditReason:`تغيير الحالة إلى ${statusLabel(next)}`});const u=users.find(x=>x.uid===uid);if(u)u.accountStatus=next;render()}catch(e){console.error(e);button.textContent='تعذر';setTimeout(()=>{button.textContent=previous;button.disabled=false},1200)}}
function render(){const list=filtered(),totalUnread=list.reduce((s,u)=>s+unread(u),0);count.textContent=`${list.length.toLocaleString('ar')} طالب · ${totalUnread.toLocaleString('ar')} تحديث جديد`;listEl.innerHTML=list.length?list.map(u=>{const n=unread(u);return`<article class="student-row ${n?'has-unread':''}" data-student-uid="${esc(u.uid)}"><span class="student-avatar">${esc((u.fullName||u.username||'ط').trim().slice(0,1))}</span><span class="student-identity"><b>${esc(u.fullName||'بدون اسم')}</b><small>@${esc(u.username||'—')}</small></span><span class="student-email">${esc(u.email||'—')}</span>${isOwner?`<span class="student-phone">الجوال: ${esc(u.phoneE164||u.phone||u.phoneLast4&&`•••• ${u.phoneLast4}`||'غير متوفر')}</span>`:''}<div class="student-meta">${n?`<span class="student-unread">${n.toLocaleString('ar')} جديد</span>`:'<span class="student-pill">تمت المراجعة</span>'}<span class="student-pill">${Number(u.xp||0).toLocaleString('ar')} XP</span><span class="student-pill">${esc(statusLabel(u.accountStatus))}</span><div class="student-status-actions"><button class="student-status-btn ${(!u.accountStatus||u.accountStatus==='active')?'is-current':''}" data-status="active" data-uid="${esc(u.uid)}" ${isOwner?'':'disabled'}>نشط</button><button class="student-status-btn ${u.accountStatus==='restricted'?'is-current':''}" data-status="restricted" data-uid="${esc(u.uid)}" ${isOwner?'':'disabled'}>مقيّد</button><button class="student-status-btn ${u.accountStatus==='suspended'?'is-current':''}" data-status="suspended" data-uid="${esc(u.uid)}" ${isOwner?'':'disabled'}>موقوف</button></div><a class="student-open" href="admin-student.html?uid=${encodeURIComponent(u.uid)}">فتح الملف ←</a></div></article>`}).join(''):'<div class="students-empty">لا يوجد طلاب مطابقون للبحث.</div>';listEl.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{const u=users.find(x=>x.uid===b.dataset.uid),next=b.dataset.status;if(!u||u.accountStatus===next||(!u.accountStatus&&next==='active'))return;setStatus(u.uid,next,b)})}
search.addEventListener('input',render);status.addEventListener('change',render);
async function load(){const [u,saved,orders,messages]=await Promise.all([read('users'),read('savedCommunityPosts'),read('orders'),read('messages')]);users=u.map(x=>({uid:x.uid||x.id,...x}));events=[];users.forEach(x=>{const at=ms(x.createdAt);if(at)events.push({uid:x.uid,at})});saved.forEach(x=>{if(x.userId)events.push({uid:x.userId,at:ms(timeOf(x))})});orders.forEach(x=>{if(x.userId)events.push({uid:x.userId,at:ms(timeOf(x))})});messages.filter(x=>x.userId&&x.type!=='service').forEach(x=>events.push({uid:x.userId,at:ms(timeOf(x))}));events=events.filter(x=>x.at);render()}
onAuthStateChanged(auth,u=>{isOwner=(u?.email||'').toLowerCase()===OWNER_EMAIL;if(u)load().catch(e=>{console.error(e);count.textContent='';listEl.innerHTML='<div class="students-error"><b>تعذر تحميل حسابات الطلاب.</b><br>تحقق من صلاحيات Firestore.</div>'})});
document.addEventListener('shadrat:student-reviewed',()=>load().catch(()=>{}));
