import { getApp, getApps, initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { browserLocalPersistence, createUserWithEmailAndPassword, deleteUser, getAuth, GoogleAuthProvider, onAuthStateChanged, sendEmailVerification, sendPasswordResetEmail, setPersistence, signInWithEmailAndPassword, signInWithPopup, signOut, updateProfile } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { doc, getDoc, getFirestore, serverTimestamp, setDoc, writeBatch } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
const OWNER_EMAIL='shadrat.almn7@gmail.com';
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
await setPersistence(auth,browserLocalPersistence).catch(()=>{});
const clean=(v='')=>String(v).trim().toLowerCase(),isOwner=(v='')=>clean(v)===OWNER_EMAIL;
const normalizeUsername=(value='')=>clean(value).replace(/^@/,'');
const reservedUsername=(value='')=>/(^|_)(owner|admin|support|staff|shazarat|شذرات|مالك|ادارة|إدارة)(_|$)/i.test(value);
const normalizePhone=(value='')=>{let p=String(value).replace(/[^\d+]/g,'');if(p.startsWith('00'))p=`+${p.slice(2)}`;if(/^05\d{8}$/.test(p))p=`+966${p.slice(1)}`;if(/^9665\d{8}$/.test(p))p=`+${p}`;return /^\+[1-9]\d{7,14}$/.test(p)?p:null};
const digest=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const errorText=(e)=>{const known={'auth/invalid-credential':'البريد الإلكتروني أو كلمة المرور غير صحيحة.','auth/email-already-in-use':'هذا البريد مستخدم في حساب آخر.','auth/weak-password':'اختر كلمة مرور أقوى لا تقل عن 10 أحرف.','auth/popup-closed-by-user':'أُغلقت نافذة Google قبل إكمال الدخول.','auth/cancelled-popup-request':'تم إلغاء نافذة Google السابقة. حاول مرة أخرى.','auth/unauthorized-domain':'نطاق الموقع غير مصرح به في Firebase.','auth/operation-not-allowed':'طريقة الدخول غير مفعلة في Firebase. فعّل Google من Authentication > Sign-in method.','auth/network-request-failed':'تعذر الاتصال. تحقق من الإنترنت وحاول مجددًا.','permission-denied':'رفضت قاعدة البيانات العملية. تحقق من صلاحيات Firestore.'};return e?.message?.includes('phone-already-used')?'رقم الجوال مستخدم في حساب آخر.':known[e?.code]||'تعذر إكمال العملية الآن. حاول مرة أخرى.'};
async function roleFor(user){if(!user)return null;if(isOwner(user.email))return'owner';try{const s=await getDoc(doc(db,'users',user.uid));return s.exists()?s.data().role:'student'}catch{return'student'}}
const show=(form,text,type='error')=>{const n=form?.querySelector('[data-auth-message]')||document.querySelector('[data-auth-message]');if(n){n.textContent=text;n.className=`auth-message ${type}`}};
const safeNext=()=>{const n=new URLSearchParams(location.search).get('next');if(!n)return null;try{const u=new URL(n,location.origin);return u.origin===location.origin?`${u.pathname.split('/').pop()||'index.html'}${u.search}${u.hash}`:null}catch{return null}};
const destination=async user=>safeNext()||(['owner','admin','support','editor','communityModerator'].includes(await roleFor(user))?'admin-analytics.html':'profile.html');
async function ensureGoogleProfile(user){const ref=doc(db,'users',user.uid),snap=await getDoc(ref);if(snap.exists())return;const base=(user.displayName||user.email?.split('@')[0]||'student').toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,16)||'student',username=`${base}_${user.uid.slice(0,5)}`.slice(0,24);await setDoc(ref,{uid:user.uid,fullName:user.displayName||'طالب شذرات',username,email:user.email||'',role:'student',accountStatus:'active',publicProfile:false,avatarKey:null,location:'',studyLevel:'',xp:0,level:1,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),authProvider:'google'});}
async function googleFlow(button){button.disabled=true;try{const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});const result=await signInWithPopup(auth,provider);await ensureGoogleProfile(result.user);location.href=await destination(result.user)}catch(e){show(document.querySelector('#login-form')||document.querySelector('#register-form'),errorText(e))}finally{button.disabled=false}}
document.querySelectorAll('[data-google-auth]').forEach(button=>button.addEventListener('click',()=>googleFlow(button)));
const loginForm=document.querySelector('#login-form');
loginForm?.addEventListener('submit',async(e)=>{e.preventDefault();if(!loginForm.reportValidity())return;const button=loginForm.querySelector('[type=submit]');button.disabled=true;try{const c=await signInWithEmailAndPassword(auth,clean(loginForm.email.value),loginForm.password.value);location.href=await destination(c.user)}catch(x){show(loginForm,errorText(x))}finally{button.disabled=false}});
document.querySelector('#reset-password')?.addEventListener('click',async(e)=>{e.preventDefault();const email=clean(loginForm?.email.value);if(!email)return show(loginForm,'اكتب بريدك الإلكتروني أولًا.');try{await sendPasswordResetEmail(auth,email);show(loginForm,'أرسلنا رابط إعادة تعيين كلمة المرور إلى بريدك.','success')}catch(x){show(loginForm,errorText(x))}});
const registerForm=document.querySelector('#register-form');
registerForm?.addEventListener('submit',async e=>{e.preventDefault();if(!registerForm.reportValidity())return;const full=registerForm.querySelector('#full').value.trim(),username=normalizeUsername(registerForm.querySelector('#username').value),email=clean(registerForm.querySelector('#mail').value),phone=normalizePhone(registerForm.querySelector('#phone').value),pass=registerForm.querySelector('#pass').value,confirm=registerForm.querySelector('#confirm').value,button=registerForm.querySelector('[type=submit]');if(!/^[a-z0-9_]{3,24}$/.test(username)||reservedUsername(username))return show(registerForm,'اسم المستخدم يجب أن يكون 3–24 حرفًا إنجليزيًا/رقمًا/شرطة سفلية وغير محجوز.');if(!phone)return show(registerForm,'اكتب رقم جوال صحيحًا بصيغة دولية.');if(pass!==confirm)return show(registerForm,'كلمتا المرور غير متطابقتين.');button.disabled=true;let created=null;try{const phoneHash=await digest(phone),cred=await createUserWithEmailAndPassword(auth,email,pass);created=cred.user;await updateProfile(created,{displayName:full});const batch=writeBatch(db),userRef=doc(db,'users',created.uid),phoneRef=doc(db,'phoneReservations',phoneHash),userNameRef=doc(db,'usernameReservations',username);batch.set(userRef,{uid:created.uid,fullName:full,username,email,phoneLast4:phone.slice(-4),role:'student',accountStatus:'active',publicProfile:false,avatarKey:null,location:'',studyLevel:'',xp:0,level:1,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),authProvider:'password'});batch.set(phoneRef,{uid:created.uid,createdAt:serverTimestamp()});batch.set(userNameRef,{uid:created.uid,createdAt:serverTimestamp()});await batch.commit();sendEmailVerification(created).catch(()=>{});location.href=await destination(created)}catch(x){console.error(x);if(created){try{await deleteUser(created)}catch{}}show(registerForm,errorText(x))}finally{button.disabled=false}});
document.querySelectorAll('[data-sign-out]').forEach(b=>b.addEventListener('click',async()=>{await signOut(auth);location.replace('login.html')}));
export{auth,db,roleFor,normalizePhone,digest};
