(() => {
  const BADGE='assets/shazarat-badge.svg';
  const addStyles=()=>{if(document.querySelector('#shazarat-badge-style'))return;const s=document.createElement('style');s.id='shazarat-badge-style';s.textContent=`
.shazarat-brand-pair{display:flex!important;align-items:center;gap:8px;overflow:visible!important;max-width:none!important}.shazarat-brand-pair .brand-logo{flex:0 1 auto}.shazarat-badge{display:block;flex:0 0 42px;width:42px;height:42px;border-radius:50%;object-fit:cover;border:1px solid #d9c9aa;background:#fff8eb;box-shadow:0 4px 13px rgba(23,53,43,.12)}
.global-menu-head .shazarat-badge{width:38px;height:38px;flex-basis:38px}.shazarat-menu-brand{display:flex;align-items:center;gap:8px;min-width:0}.shazarat-admin-brand{display:flex;align-items:center;gap:10px;padding:10px 9px 14px;margin-bottom:8px;border-bottom:1px solid #e5ddce;color:#17352b}.shazarat-admin-brand .shazarat-badge{width:46px;height:46px;flex-basis:46px}.shazarat-admin-brand b,.shazarat-admin-brand small{display:block}.shazarat-admin-brand b{font-size:13px}.shazarat-admin-brand small{margin-top:2px;font-size:10px;color:#78847e}
@media(max-width:820px){.site-header .shazarat-badge,.global-site-header .shazarat-badge{width:38px;height:38px;flex-basis:38px}.shazarat-brand-pair{gap:6px}}
@media(max-width:390px){.site-header .shazarat-badge,.global-site-header .shazarat-badge{width:34px;height:34px;flex-basis:34px}}
`;document.head.appendChild(s)};
  const addFavicon=()=>{let f=document.querySelector('link[rel~="icon"][data-shazarat-badge]');if(!f){f=document.createElement('link');f.rel='icon';f.type='image/svg+xml';f.href=BADGE;f.dataset.shazaratBadge='1';document.head.appendChild(f)}let a=document.querySelector('link[rel="apple-touch-icon"][data-shazarat-badge]');if(!a){a=document.createElement('link');a.rel='apple-touch-icon';a.href=BADGE;a.dataset.shazaratBadge='1';document.head.appendChild(a)}};
  const pairHeaderBrand=()=>{document.querySelectorAll('header .brand').forEach(brand=>{if(brand.querySelector('.shazarat-badge'))return;brand.classList.add('shazarat-brand-pair');const badge=document.createElement('img');badge.src=BADGE;badge.alt='';badge.className='shazarat-badge';badge.setAttribute('aria-hidden','true');brand.appendChild(badge)})};
  const pairHamburgerBrand=()=>{document.querySelectorAll('.global-menu-head').forEach(head=>{if(head.querySelector('.shazarat-badge'))return;const old=head.querySelector('.brand-logo');if(!old)return;const box=document.createElement('div');box.className='shazarat-menu-brand';old.before(box);box.append(old);const badge=document.createElement('img');badge.src=BADGE;badge.alt='';badge.className='shazarat-badge';badge.setAttribute('aria-hidden','true');box.appendChild(badge)})};
  const addAdminBrand=()=>{document.querySelectorAll('.admin-nav').forEach(nav=>{if(nav.querySelector('.shazarat-admin-brand'))return;const brand=document.createElement('div');brand.className='shazarat-admin-brand';brand.innerHTML=`<img class="shazarat-badge" src="${BADGE}" alt=""><span><b>شذرات للمنح</b><small>لوحة الإدارة</small></span>`;nav.prepend(brand)})};
  const addStructuredLogo=()=>{if(location.pathname.split('/').pop()?.startsWith('admin-')||document.querySelector('script[data-shazarat-org]'))return;const sc=document.createElement('script');sc.type='application/ld+json';sc.dataset.shazaratOrg='1';sc.textContent=JSON.stringify({'@context':'https://schema.org','@type':'Organization','name':'شذرات للمنح','url':'https://shadratalmn7-sudo.github.io/','logo':'https://shadratalmn7-sudo.github.io/assets/shazarat-badge.svg'});document.head.appendChild(sc)};
  const run=()=>{addStyles();addFavicon();pairHeaderBrand();pairHamburgerBrand();addAdminBrand();addStructuredLogo()};
  run();let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;run()})}).observe(document.documentElement,{childList:true,subtree:true});
})();