import{downloadNodePdf,getArtifact,safeFilename,saveArtifact,waitForUser}from'./student-artifacts-a4.js?v=7';
import{certificateEvidence,extractCertificateInfo,readCertificate,skillLabels}from'./certificate-reader.js?v=3';
import{buildSemanticCv}from'./cv-semantic-polish.js?v=6';
const $=id=>document.getElementById(id),clean=v=>String(v||'').trim(),lines=v=>String(v||'').split(/\n+/).map(clean).filter(Boolean),splitSkills=v=>String(v||'').split(/[،,|•\n]+/).map(clean).filter(Boolean);
const fieldIds=['artifactName','name','role','email','phone','location','link','summary','education','certs','experience','skills','languages','institution','destination','studyGoal','employer','workGoal','template','lang'];
const templates=[['formal','رسمي','هادئ ومناسب للمنح'],['editorial','صحيفة','Editorial بعمودين'],['modern','حديث','هيدر قوي ومساحات واضحة'],['sidebar','جانبي','معلومات جانبية ومحتوى رئيسي'],['academic','أكاديمي','جامعي كلاسيكي'],['creative','إبداعي','بطاقات ولمسات مرئية'],['technical','تقني','مظهر برمجي منظم'],['executive','تنفيذي','رسمي داكن ومميز'],['timeline','Timeline','أقسام على خط زمني'],['minimal','Minimal','أبيض وبسيط جدًا']];
let certificates=[],mode='auto',purpose='study',groupId=crypto.randomUUID(),version=1,lastSavedFingerprint='',saving=false;
const localKey='shadrat-cv-v5',esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const collect=()=>Object.fromEntries(fieldIds.map(id=>[id,$(id)?.value||'']));
const fingerprint=data=>JSON.stringify({data,mode,purpose,certificates:certificates.map(c=>c.info||{fileName:c.fileName,error:true})});
const status=(text,type='')=>{const el=$('builderStatus');if(el){el.textContent=text;el.className=`builder-status ${type}`.trim()}};
function fillList(id,items){const el=$(id);el.innerHTML='';items.filter(Boolean).forEach(x=>{const li=document.createElement('li');li.textContent=x;el.appendChild(li)})}
function toggle(id,show){const s=$(id)?.closest('section');if(s)s.hidden=!show}
const arDigits=v=>String(v||'').replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d));
function statedCertificateCount(data){const text=arDigits([data.summary,data.education,data.certs].join(' ')),m=text.match(/(\d{1,3})\s*(?:شهاد|دور|certificate|course)/i);return m?Number(m[1]):0}
function isCertificateCountOnly(v){return /^(?=.{0,100}$).*(?:عندي|لدي|حاصل|حاصلة|امتلك|أمتلك|have|hold).*(?:\d+|[٠-٩]+)\s*(?:شهاد|دور|certificate|course)/i.test(v)&&!/[-—:]/.test(v)}
function certItems(data,lang){const manual=lines(data.certs).map(x=>{if(mode==='manual'||!isCertificateCountOnly(x))return x;const count=statedCertificateCount({summary:'',education:'',certs:x});return lang==='ar'?`سجل تعلم موثق يضم ${count||'عدة'} شهادة ودورة تدريبية، مع عرض تفاصيل كل شهادة مرفوعة بصورة مستقلة.`:`Documented learning portfolio comprising ${count||'multiple'} certificates and training courses, with each uploaded credential presented separately.`});return[...manual,...certificates.filter(c=>!c.error&&c.info).map(c=>certificateEvidence(c.info,lang))]}
function rewriteGoal(v,lang,work=false){const text=clean(v).replace(/^(?:أنا|انا|أريد|اريد|أبغى|ابغى|هدفي|I want|My goal is)\s*/i,'').replace(/[.،,]+$/,'');if(!text)return'';if(lang==='ar')return work?`أسعى إلى توظيف قدراتي وتطويرها ضمن مسار مهني يركز على ${text}، مع الالتزام بالتعلم المستمر والعمل المسؤول.`:`أسعى إلى بناء مسار أكاديمي منظم يركز على ${text}، وتحويل هذا الاهتمام إلى معرفة أعمق ومخرجات قابلة للتقييم.`;return work?`Seeking to apply and further develop my capabilities through a professional path focused on ${text}, with a commitment to continuous learning and responsible work.`:`Seeking a structured academic path focused on ${text}, turning this interest into deeper knowledge and measurable outcomes.`}
function objective(data,lang){if(mode==='manual')return purpose==='study'?clean(data.studyGoal):clean(data.workGoal);if(purpose==='study')return lang==='ar'?[rewriteGoal(data.studyGoal,lang),data.institution&&`الجهة الأكاديمية المستهدفة: ${data.institution}.`,data.destination&&`وجهة الدراسة المستهدفة: ${data.destination}.`].filter(Boolean).join(' '):[rewriteGoal(data.studyGoal,lang),data.institution&&`Target academic institution: ${data.institution}.`,data.destination&&`Target study destination: ${data.destination}.`].filter(Boolean).join(' ');return lang==='ar'?[rewriteGoal(data.workGoal,lang,true),data.employer&&`جهة العمل المستهدفة: ${data.employer}.`].filter(Boolean).join(' '):[rewriteGoal(data.workGoal,lang,true),data.employer&&`Target employer: ${data.employer}.`].filter(Boolean).join(' ')}
function render(){const data=collect(),lang=data.lang==='ar'?'ar':'en',rawSkills=[...new Set([...splitSkills(data.skills),...certificates.flatMap(c=>c.info?skillLabels(c.info,lang):[])])],certs=certItems(data,lang),semantic=mode==='auto'?buildSemanticCv(data,{certificateCount:certs.length,skills:rawSkills}):null;const headline=mode==='manual'?clean(data.role):(semantic?.headline||clean(data.role)),summary=mode==='manual'?clean(data.summary):(semantic?.summary||clean(data.summary)),education=mode==='manual'?lines(data.education):(semantic?.education||lines(data.education)),experience=mode==='manual'?lines(data.experience):(semantic?.experience||lines(data.experience)),skills=mode==='manual'?splitSkills(data.skills):(semantic?.skills?.length?semantic.skills:rawSkills),languages=mode==='manual'?clean(data.languages):(semantic?.languages||clean(data.languages)),obj=objective(data,lang);$('pName').textContent=clean(data.name)||(lang==='ar'?'الاسم الكامل':'Full Name');$('pRole').textContent=headline;$('pSummary').textContent=summary;$('pObjective').textContent=obj;fillList('pEducation',education);fillList('pCerts',certs);fillList('pExperience',experience);$('pSkills').textContent=skills.join(' • ');$('pLanguages').textContent=languages;$('pContact').textContent=[data.email,data.phone,data.location,data.link].map(clean).filter(Boolean).join(' • ')||(lang==='ar'?'بيانات التواصل':'Contact details');toggle('pSummary',!!summary);toggle('pObjective',!!obj);toggle('pEducation',education.length);toggle('pCerts',certs.length);toggle('pExperience',experience.length);toggle('pSkills',skills.length);toggle('pLanguages',!!languages);const cv=$('cv');cv.className=`cv template-${data.template||'formal'} cv-${mode}`;cv.dir=lang==='ar'?'rtl':'ltr';cv.dataset.multipage='true';const ar={summary:'النبذة',objective:purpose==='study'?'الهدف الدراسي':'الهدف المهني',education:'التعليم',certs:'الشهادات والإنجازات',experience:'الخبرات والمشاريع',skills:'المهارات',languages:'اللغات'},en={summary:'PROFILE',objective:purpose==='study'?'ACADEMIC OBJECTIVE':'CAREER OBJECTIVE',education:'EDUCATION',certs:'CERTIFICATES & ACHIEVEMENTS',experience:'EXPERIENCE & PROJECTS',skills:'SKILLS',languages:'LANGUAGES'};document.querySelectorAll('#cv [data-key]').forEach(el=>el.textContent=(lang==='ar'?ar:en)[el.dataset.key]);document.querySelectorAll('[data-cv-template]').forEach(b=>b.classList.toggle('is-active',b.dataset.cvTemplate===data.template));renderCertificates();saveLocal();window.ShadratFitA4Preview?.()}
function renderCertificates(){const box=$('cvCertResults');if(!box)return;const lang=$('lang').value==='ar'?'ar':'en';box.innerHTML=certificates.map((c,i)=>c.error?`<div class="cert-result error"><b>${esc(c.fileName)}</b><span>تعذر استخراج نص كافٍ.</span><button type="button" class="cert-remove" data-remove-cert="${i}">حذف</button></div>`:`<div class="cert-result"><b>${esc(c.info.course||c.info.title||c.fileName)}</b><span>${esc([c.info.issuer,c.info.date,c.sourcePage&&`صفحة ${c.sourcePage}`].filter(Boolean).join(' · '))}</span><small class="cert-evidence">${esc(certificateEvidence(c.info,lang))}</small><button type="button" class="cert-remove" data-remove-cert="${i}">حذف</button></div>`).join('');box.querySelectorAll('[data-remove-cert]').forEach(b=>b.onclick=()=>{certificates.splice(+b.dataset.removeCert,1);render()})}
function setMode(next){mode=next==='manual'?'manual':'auto';document.querySelectorAll('[data-cv-mode]').forEach(b=>b.classList.toggle('is-active',b.dataset.cvMode===mode));$('cvModeHelp').textContent=mode==='manual'?'سيظهر نصك كما كتبته دون إعادة صياغة.':'اكتب الحقائق باختصار، وسيصوغها الموقع مهنيًا دون اختراع معلومات.';render()}
function setPurpose(next){purpose=next==='work'?'work':'study';document.querySelectorAll('[data-cv-purpose]').forEach(b=>b.classList.toggle('is-active',b.dataset.cvPurpose===purpose));document.querySelectorAll('[data-study-field]').forEach(x=>x.hidden=purpose!=='study');document.querySelectorAll('[data-work-field]').forEach(x=>x.hidden=purpose!=='work');render()}
function saveLocal(){try{localStorage.setItem(localKey,JSON.stringify({groupId,version,mode,purpose,data:collect(),certificates}))}catch{}}
function setupTemplates(){const box=$('templatePicker');box.innerHTML=templates.map(([id,label,desc])=>`<button type="button" class="template-choice template-choice-${id}" data-cv-template="${id}"><b>${label}</b><small>${desc}</small></button>`).join('');box.onclick=e=>{const b=e.target.closest('[data-cv-template]');if(b){$('template').value=b.dataset.cvTemplate;render()}}}
async function readCertificates(files){for(const file of[...files].slice(0,20)){status(`جاري قراءة ${file.name}…`);try{const result=await readCertificate(file,{onProgress:p=>status(`جاري قراءة ${file.name}… ${p}%`)});certificates.push(...(result.items||[result]));status(`تمت قراءة ${file.name} بالكامل وإضافة بياناتها.`,'success')}catch(error){console.error(error);certificates.push({fileName:file.name,error:true});status(`تعذر قراءة ${file.name}. جرّب نسخة أوضح.`,'error')}render()}$('cvCertFiles').value=''}
async function saveCloud({silent=false}={}){if(saving)return null;const data=collect(),user=await waitForUser();if(!user){if(!silent)status('سجّل الدخول لحفظ السيرة في حسابك.','error');return null}saving=true;try{const saved=await saveArtifact({artifactType:'cv',artifactGroupId:groupId,artifactName:data.artifactName||'CV 1',studentName:data.name,specialization:data.role,program:data.institution||data.employer,template:data.template,language:data.lang,version,data:{...data,mode,purpose},renderedHtml:$('cv').outerHTML,renderedText:$('cv').innerText,certificateSummaries:certificates.filter(c=>c.info).map(c=>c.info)});lastSavedFingerprint=fingerprint(data);version++;saveLocal();if(!silent)status('تم حفظ السيرة في حسابك.','success');return saved}catch(e){console.error(e);if(!silent)status('تعذر الحفظ الآن.','error');return null}finally{saving=false}}
async function download(){render();const data=collect(),btn=$('downloadBtn'),old=btn.textContent;btn.disabled=true;btn.textContent='جاري تجهيز PDF…';try{const user=await waitForUser(1200);if(user&&fingerprint(data)!==lastSavedFingerprint)await saveCloud({silent:true});await downloadNodePdf($('cv'),`${safeFilename(data.name,'Student')}-CV.pdf`);status('تم تنزيل السيرة PDF بكل صفحاتها.','success')}catch(e){console.error(e);status('تعذر تجهيز PDF الآن.','error')}finally{btn.disabled=false;btn.textContent=old}}
async function loadInitial(){setupTemplates();document.querySelectorAll('[data-cv-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.cvMode));document.querySelectorAll('[data-cv-purpose]').forEach(b=>b.onclick=()=>setPurpose(b.dataset.cvPurpose));const id=new URLSearchParams(location.search).get('artifact');let saved=null;if(id)try{const a=await getArtifact(id);if(a?.artifactType==='cv')saved={groupId:a.artifactGroupId,version:+a.version+1,mode:a.data?.mode,purpose:a.data?.purpose,data:a.data,certificates:(a.certificateSummaries||[]).map(info=>({fileName:info.fileName||'',info}))}}catch(e){console.warn(e)}if(!saved)try{saved=JSON.parse(localStorage.getItem(localKey)||'null')}catch{}if(saved?.data){groupId=saved.groupId||groupId;version=saved.version||version;mode=saved.mode||'auto';purpose=saved.purpose||'study';certificates=saved.certificates||[];fieldIds.forEach(id=>{if($(id)&&saved.data[id]!=null)$(id).value=saved.data[id]})}else{const user=await waitForUser(700);if(user)$('name').value=user.displayName||''}setPurpose(purpose);setMode(mode)}
fieldIds.forEach(id=>$(id)?.addEventListener('input',render));$('cvCertFiles')?.addEventListener('change',e=>readCertificates(e.target.files));$('downloadBtn')?.addEventListener('click',download);$('clearBtn')?.addEventListener('click',()=>{if(!confirm('مسح جميع البيانات الحالية؟'))return;fieldIds.forEach(id=>{if($(id))$(id).value=id==='template'?'formal':id==='lang'?'en':''});certificates=[];mode='auto';purpose='study';groupId=crypto.randomUUID();version=1;setPurpose(purpose);setMode(mode)});loadInitial();
