if (!window.__shadratDocsUnifiedReady) {
  window.__shadratDocsUnifiedReady = true;

  const fromEl = document.querySelector('#convert-from');
  const toEl = document.querySelector('#convert-to');
  const area = document.querySelector('#active-tool-area');
  let currentUrl = '';

  const formats = [
    { value: 'image', label: 'صورة' },
    { value: 'pdf', label: 'PDF' },
    { value: 'txt', label: 'نص TXT' },
    { value: 'word', label: 'Word' },
    { value: 'excel', label: 'Excel' },
    { value: 'powerpoint', label: 'PowerPoint' }
  ];
  const labels = Object.fromEntries(formats.map(item => [item.value, item.label]));
  const isIOS = /iPad|iPhone|iPod/.test(navigator.userAgent) || (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1);

  const loadPdfLib = async () => import('https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/+esm');
  const loadZip = async () => (await import('https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm')).default;
  const loadPdfJs = async () => {
    const pdfjs = await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/+esm');
    pdfjs.GlobalWorkerOptions.workerSrc = 'https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.mjs';
    return pdfjs;
  };
  const revokeOld = () => { if (currentUrl) URL.revokeObjectURL(currentUrl); currentUrl = ''; };
  const readBytes = file => file.arrayBuffer();
  const setStatus = text => { const status = area?.querySelector('[data-status]'); if (status) status.textContent = text; };
  const canvasBlob = (canvas, type, quality = 0.9) => new Promise(resolve => canvas.toBlob(resolve, type, quality));
  const blobToDataUrl = blob => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(blob); });

  const makeDownload = async (blob, name) => {
    revokeOld();
    const link = area.querySelector('[data-download]');
    const openLink = area.querySelector('[data-open-result]');
    const shareButton = area.querySelector('[data-share-result]');
    currentUrl = URL.createObjectURL(blob);
    link.href = currentUrl;
    link.download = name;
    link.hidden = false;
    link.textContent = 'تحميل الملف الجاهز';
    if (openLink) { openLink.href = currentUrl; openLink.hidden = false; openLink.textContent = 'فتح الناتج'; }
    if (shareButton && navigator.canShare) {
      try { const file = new File([blob], name, { type: blob.type || 'application/octet-stream' }); if (navigator.canShare({ files: [file] })) { shareButton.hidden = false; shareButton.onclick = async () => navigator.share({ files: [file], title: name }); } } catch (_) {}
    }
    if (isIOS && blob.size < 18 * 1024 * 1024) {
      try { const dataUrl = await blobToDataUrl(blob); link.href = dataUrl; if (openLink) openLink.href = dataUrl; } catch (_) {}
    }
    link.onclick = () => { if (isIOS && openLink?.href) setTimeout(() => { try { window.open(openLink.href, '_blank', 'noopener'); } catch (_) {} }, 140); };
    setStatus('تم التحويل. إذا لم يبدأ التحميل تلقائيًا اضغط تحميل الملف الجاهز أو فتح الناتج.');
    setTimeout(() => { try { link.click(); } catch (_) {} }, 120);
  };
  const downloadPdf = (bytes, name) => makeDownload(new Blob([bytes], { type: 'application/pdf' }), name);
  const textDownload = (text, name) => makeDownload(new Blob([text], { type: 'text/plain;charset=utf-8' }), name);

  const fillFormats = () => {
    const html = formats.map(item => `<option value="${item.value}">${item.label}</option>`).join('');
    fromEl.innerHTML = html; toEl.innerHTML = html; fromEl.value = 'image'; toEl.value = 'pdf';
  };
  const loadImage = file => new Promise((resolve, reject) => { const url = URL.createObjectURL(file); const img = new Image(); img.onload = () => { URL.revokeObjectURL(url); resolve(img); }; img.onerror = () => { URL.revokeObjectURL(url); reject(new Error('تعذر قراءة الصورة.')); }; img.src = url; });
  const imageToCanvas = async (file, maxWidth = null) => { const img = await loadImage(file); const scale = maxWidth ? Math.min(1, maxWidth / img.width) : 1; const canvas = document.createElement('canvas'); canvas.width = Math.round(img.width * scale); canvas.height = Math.round(img.height * scale); canvas.getContext('2d').drawImage(img, 0, 0, canvas.width, canvas.height); return canvas; };
  const getFiles = () => [...(area.querySelector('input[type="file"]')?.files || [])];
  const parseRanges = (value, total) => { const pages = new Set(); String(value || '').split(',').map(part => part.trim()).filter(Boolean).forEach(part => { const match = part.match(/^(\d+)(?:\s*-\s*(\d+))?$/); if (!match) throw new Error('صيغة الصفحات غير صحيحة. اكتب مثل: 1-3, 5'); const start = Number(match[1]); const end = Number(match[2] || match[1]); if (start < 1 || end < start || end > total) throw new Error(`اختر صفحات بين 1 و ${total}.`); for (let page = start; page <= end; page += 1) pages.add(page - 1); }); return [...pages]; };

  const imagesToPdf = async files => { if (!files.length) throw new Error('اختر صورة واحدة على الأقل.'); const { PDFDocument } = await loadPdfLib(); const pdf = await PDFDocument.create(); const pageWidth = 595.28, pageHeight = 841.89, margin = 32; for (const file of files) { let bytes = await readBytes(file), type = file.type; if (type === 'image/webp') { const canvas = await imageToCanvas(file); const blob = await canvasBlob(canvas, 'image/png'); bytes = await blob.arrayBuffer(); type = 'image/png'; } const image = type === 'image/png' ? await pdf.embedPng(bytes) : await pdf.embedJpg(bytes); const scale = Math.min((pageWidth - margin * 2) / image.width, (pageHeight - margin * 2) / image.height); const width = image.width * scale, height = image.height * scale; const page = pdf.addPage([pageWidth, pageHeight]); page.drawImage(image, { x: (pageWidth - width) / 2, y: (pageHeight - height) / 2, width, height }); } await downloadPdf(await pdf.save(), 'shadrat-images.pdf'); };
  const pdfToImages = async files => { const file = files[0]; if (!file) throw new Error('اختر ملف PDF أولًا.'); const [pdfjs, JSZip] = await Promise.all([loadPdfJs(), loadZip()]); const pdf = await pdfjs.getDocument({ data: await readBytes(file) }).promise; const zip = new JSZip(); for (let i = 1; i <= pdf.numPages; i += 1) { const page = await pdf.getPage(i), viewport = page.getViewport({ scale: 2 }); const canvas = document.createElement('canvas'); canvas.width = viewport.width; canvas.height = viewport.height; await page.render({ canvasContext: canvas.getContext('2d'), viewport }).promise; zip.file(`page-${String(i).padStart(2, '0')}.png`, await canvasBlob(canvas, 'image/png')); } await makeDownload(await zip.generateAsync({ type: 'blob' }), 'shadrat-pdf-images.zip'); };
  const pdfToText = async files => { const file = files[0]; if (!file) throw new Error('اختر ملف PDF أولًا.'); const pdfjs = await loadPdfJs(); const pdf = await pdfjs.getDocument({ data: await readBytes(file) }).promise; const pages = []; for (let i = 1; i <= pdf.numPages; i += 1) { const page = await pdf.getPage(i); const content = await page.getTextContent(); pages.push(`صفحة ${i}\n${content.items.map(item => item.str).join(' ')}`); } await textDownload(pages.join('\n\n--------------------\n\n'), 'shadrat-pdf-text.txt'); };
  const mergePdf = async files => { if (files.length < 2) throw new Error('اختر ملفين PDF على الأقل للدمج.'); const { PDFDocument } = await loadPdfLib(); const output = await PDFDocument.create(); for (const file of files) { const source = await PDFDocument.load(await readBytes(file)); const pages = await output.copyPages(source, source.getPageIndices()); pages.forEach(page => output.addPage(page)); } await downloadPdf(await output.save(), 'shadrat-merged.pdf'); };
  const splitPdf = async (files, ranges) => { const file = files[0]; if (!file) throw new Error('اختر ملف PDF أولًا.'); if (!ranges.trim()) throw new Error('اكتب الصفحات المطلوبة.'); const { PDFDocument } = await loadPdfLib(); const source = await PDFDocument.load(await readBytes(file)); const output = await PDFDocument.create(); const pages = await output.copyPages(source, parseRanges(ranges, source.getPageCount())); pages.forEach(page => output.addPage(page)); await downloadPdf(await output.save(), 'shadrat-pages.pdf'); };
  const removePages = async (files, ranges) => { const file = files[0]; if (!file) throw new Error('اختر ملف PDF أولًا.'); if (!ranges.trim()) throw new Error('اكتب الصفحات التي تريد حذفها.'); const { PDFDocument } = await loadPdfLib(); const source = await PDFDocument.load(await readBytes(file)); const output = await PDFDocument.create(); const removed = new Set(parseRanges(ranges, source.getPageCount())); const keep = source.getPageIndices().filter(index => !removed.has(index)); if (!keep.length) throw new Error('لا يمكن حذف كل الصفحات. اترك صفحة واحدة على الأقل.'); const pages = await output.copyPages(source, keep); pages.forEach(page => output.addPage(page)); await downloadPdf(await output.save(), 'shadrat-removed-pages.pdf'); };
  const rotatePdf = async (files, angle) => { const file = files[0]; if (!file) throw new Error('اختر ملف PDF أولًا.'); const { PDFDocument, degrees } = await loadPdfLib(); const pdf = await PDFDocument.load(await readBytes(file)); pdf.getPages().forEach(page => page.setRotation(degrees(Number(angle || 90)))); await downloadPdf(await pdf.save(), 'shadrat-rotated.pdf'); };
  const convertImage = async (files, action) => { const file = files[0]; if (!file) throw new Error('اختر صورة أولًا.'); const maxWidth = action === 'resize-image' ? Number(area.querySelector('[data-max-width]')?.value || 1200) : null; const quality = Number(area.querySelector('[data-quality]')?.value || 0.85); const canvas = await imageToCanvas(file, maxWidth); const type = action === 'image-to-png' ? 'image/png' : action === 'image-to-webp' || action === 'resize-image' ? 'image/webp' : 'image/jpeg'; const ext = type === 'image/png' ? 'png' : type === 'image/webp' ? 'webp' : 'jpg'; await makeDownload(await canvasBlob(canvas, type, quality), `shadrat-image.${ext}`); };

  const getTool = () => { const from = fromEl.value, to = toEl.value; if (from === 'image' && to === 'pdf') return { kind: 'image-pdf', title: 'صورة إلى PDF', hint: 'شغال الآن: حوّل صورة أو عدة صور إلى PDF واحد.', badge: 'PDF' }; if (from === 'pdf' && to === 'image') return { kind: 'pdf-image', title: 'PDF إلى صور', hint: 'شغال الآن: حوّل صفحات PDF إلى صور PNG داخل ملف ZIP.', badge: 'PNG' }; if (from === 'pdf' && to === 'txt') return { kind: 'pdf-text', title: 'PDF إلى نص TXT', hint: 'شغال الآن: استخراج النص من PDF قابل للنسخ.', badge: 'TXT' }; if (from === 'pdf' && to === 'pdf') return { kind: 'pdf-tools', title: 'أدوات PDF', hint: 'شغال الآن: دمج، استخراج، حذف، أو تدوير صفحات PDF.', badge: 'PDF' }; if (from === 'image' && to === 'image') return { kind: 'image-tools', title: 'أدوات الصور', hint: 'شغال الآن: تحويل JPG / PNG / WebP أو ضغط الصورة.', badge: 'IMG' }; return { kind: 'soon', title: `${labels[from]} إلى ${labels[to]}`, hint: 'قريبًا: هذا التحويل يحتاج خادم معالجة آمن.', badge: 'قريبًا' }; };
  const drawInputs = tool => { const inputs = area.querySelector('[data-inputs]'); if (!inputs) return; const pdfAction = area.querySelector('[data-pdf-action]')?.value || 'merge-pdf'; const imageAction = area.querySelector('[data-image-action]')?.value || 'image-to-jpg'; const isPdfTool = tool.kind === 'pdf-tools', isImageTool = tool.kind === 'image-tools'; const accept = isPdfTool || tool.kind === 'pdf-image' || tool.kind === 'pdf-text' ? 'application/pdf' : 'image/jpeg,image/png,image/webp'; const multiple = tool.kind === 'image-pdf' || (isPdfTool && pdfAction === 'merge-pdf'); inputs.innerHTML = `<label class="drop-zone"><input type="file" accept="${accept}" ${multiple ? 'multiple' : ''}><b>ادخل الملف هنا</b><small>${multiple ? 'يمكن اختيار أكثر من ملف' : 'اختر ملف واحد من جهازك'}</small></label>${isPdfTool && ['split-pdf','remove-pages'].includes(pdfAction) ? '<label class="field"><span>الصفحات</span><input data-ranges type="text" placeholder="مثال: 1-3, 5"></label>' : ''}${isPdfTool && pdfAction === 'rotate-pdf' ? '<label class="field"><span>زاوية التدوير</span><select data-angle><option value="90">90 درجة</option><option value="180">180 درجة</option><option value="270">270 درجة</option></select></label>' : ''}${isImageTool && imageAction === 'resize-image' ? '<div class="tool-options"><label class="field"><span>العرض الأقصى</span><input data-max-width type="number" min="200" max="4000" value="1200"></label><label class="field"><span>الجودة</span><select data-quality><option value="0.85">عالية</option><option value="0.7">متوسطة</option><option value="0.55">حجم أصغر</option></select></label></div>' : ''}`; inputs.querySelector('input[type="file"]')?.addEventListener('change', event => { const names = [...event.target.files].map(f => f.name).join('، '); setStatus(names ? `تم اختيار: ${names}` : 'اختر ملفًا للبدء.'); }); };
  const renderTool = () => { revokeOld(); const tool = getTool(); area.innerHTML = `<div class="tool-card"><div class="tool-card-head"><div><span class="tool-badge">${tool.badge}</span><h3>${tool.title}</h3><p>${tool.hint}</p></div></div>${tool.kind === 'pdf-tools' ? '<label class="field"><span>العملية</span><select data-pdf-action><option value="merge-pdf">دمج ملفات PDF</option><option value="split-pdf">استخراج صفحات محددة</option><option value="remove-pages">حذف صفحات محددة</option><option value="rotate-pdf">تدوير PDF</option></select></label>' : ''}${tool.kind === 'image-tools' ? '<label class="field"><span>العملية</span><select data-image-action><option value="image-to-jpg">تحويل إلى JPG</option><option value="image-to-png">تحويل إلى PNG</option><option value="image-to-webp">تحويل إلى WebP</option><option value="resize-image">ضغط / تصغير الصورة</option></select></label>' : ''}<div data-inputs></div><div class="tool-actions"><button class="btn primary" data-run ${tool.kind === 'soon' ? 'disabled' : ''}>تحويل الآن</button><a class="btn outline" data-download hidden>تحميل الملف الجاهز</a><a class="btn outline" data-open-result target="_blank" rel="noopener" hidden>فتح الناتج</a><button class="btn outline" type="button" data-share-result hidden>مشاركة / حفظ</button></div><p class="status-line" data-status>${tool.kind === 'soon' ? 'هذا التحويل غير مفعل الآن.' : 'اختر الملف ثم اضغط تحويل الآن.'}</p></div>`; drawInputs(tool); area.querySelector('[data-pdf-action]')?.addEventListener('change', () => drawInputs(tool)); area.querySelector('[data-image-action]')?.addEventListener('change', () => drawInputs(tool)); area.querySelector('[data-run]')?.addEventListener('click', async () => { const button = area.querySelector('[data-run]'); try { button.disabled = true; revokeOld(); area.querySelector('[data-download]').hidden = true; area.querySelector('[data-open-result]').hidden = true; area.querySelector('[data-share-result]').hidden = true; setStatus('جاري التحويل داخل المتصفح…'); const files = getFiles(); if (tool.kind === 'image-pdf') await imagesToPdf(files); else if (tool.kind === 'pdf-image') await pdfToImages(files); else if (tool.kind === 'pdf-text') await pdfToText(files); else if (tool.kind === 'pdf-tools') { const action = area.querySelector('[data-pdf-action]').value; if (action === 'merge-pdf') await mergePdf(files); if (action === 'split-pdf') await splitPdf(files, area.querySelector('[data-ranges]')?.value || ''); if (action === 'remove-pages') await removePages(files, area.querySelector('[data-ranges]')?.value || ''); if (action === 'rotate-pdf') await rotatePdf(files, area.querySelector('[data-angle]')?.value || 90); } else if (tool.kind === 'image-tools') await convertImage(files, area.querySelector('[data-image-action]').value); } catch (error) { console.error(error); setStatus(error.message || 'تعذر التحويل.'); } finally { button.disabled = false; } }); };
  fillFormats(); renderTool(); fromEl.addEventListener('change', renderTool); toEl.addEventListener('change', renderTool); document.querySelector('#swap-conversion')?.addEventListener('click', () => { const x = fromEl.value; fromEl.value = toEl.value; toEl.value = x; renderTool(); });
}
