import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{firebaseConfig}from'./firebase-config.js';
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app);
function makeLink(el,href){if(!el||el.tagName==='A')return;const a=document.createElement('a');a.className=el.className;a.href=href;a.innerHTML=el.innerHTML;for(const attr of el.attributes)if(!['class'].includes(attr.name))a.setAttribute(attr.name,attr.value);el.replaceWith(a)}
function addHomepageAd(){if(document.querySelector('[data-shazarat-ad-unit]'))return;const target=document.querySelector('.featured');if(!target)return;const wrap=document.createElement('div');wrap.dataset.shazaratAdUnit='';wrap.style.cssText='width:min(100% - 24px,760px);min-height:50px;margin:22px auto;text-align:center;overflow:hidden;';const ad=document.createElement('ins');ad.className='adsbygoogle';ad.style.cssText='display:block;width:100%;min-height:50px';ad.setAttribute('data-ad-client','ca-pub-9420608712266016');ad.setAttribute('data-ad-slot','7940675517');ad.setAttribute('data-ad-format','horizontal');ad.setAttribute('data-full-width-responsive','true');wrap.appendChild(ad);target.insertAdjacentElement('afterend',wrap);try{(window.adsbygoogle=window.adsbygoogle||[]).push({})}catch(e){console.warn('AdSense unit pending',e)}}
function repairHomepage(){if(!location.pathname.endsWith('/')&&!location.pathname.endsWith('/index.html'))return;
 document.querySelectorAll('.featured article').forEach(card=>{const title=card.querySelector('h3')?.textContent||'';const detail=card.querySelector('.detail');if(/التركية|تركيا/.test(title))makeLink(detail,'turkiye-scholarships.html')});
 const all=[...document.querySelectorAll('.section-head b')].find(x=>/عرض جميع المنح/.test(x.textContent||''));makeLink(all,'scholarships.html');
 document.querySelectorAll('.cta .outline,.banner .dark').forEach(el=>{if(/حساب|ابدأ|إنشاء/.test(el.textContent||'')){el.dataset.guestOnly='';makeLink(el,'register.html')}});addHomepageAd();
}
repairHomepage();
onAuthStateChanged(auth,user=>{document.querySelectorAll('[data-guest-only]').forEach(el=>el.hidden=!!user);if(user){document.querySelectorAll('.cta').forEach(area=>{if(!area.querySelector('[data-account-cta]')){const a=document.createElement('a');a.href='profile.html';a.className='btn outline';a.dataset.accountCta='';a.textContent='اذهب إلى حسابي';area.appendChild(a)}});const banner=document.querySelector('.banner');if(banner){const b=banner.querySelector('b'),h=banner.querySelector('h2'),p=banner.querySelector('p');if(b)b.textContent='مرحبًا بعودتك';if(h)h.textContent='تابع فرصك وخطواتك من حسابك';if(p)p.textContent='راجع المنح المحفوظة والمهمات والطلبات والتنبيهات من مكان واحد.';if(!banner.querySelector('[data-account-banner]')){const a=document.createElement('a');a.href='profile.html';a.className='dark';a.dataset.accountBanner='';a.textContent='فتح حسابي';banner.appendChild(a)}}}});
