import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';import{collection,getDocs,getFirestore,query,where}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';import{firebaseConfig}from'./firebase-config.js';import{mergeScholarships}from'./scholarship-catalog.js';
if(location.pathname.endsWith('/')||location.pathname.endsWith('/index.html')){
 const cta=document.querySelector('.hero .cta');if(cta)cta.querySelectorAll('[data-social-placeholder]').forEach(x=>x.remove());
 const stats=document.querySelectorAll('.stats .stat b');const paintStats=items=>{const countries=new Set(items.map(x=>x.country).filter(Boolean));if(stats[0])stats[0].textContent=items.length.toLocaleString('ar');if(stats[1])stats[1].textContent=countries.size.toLocaleString('ar');if(stats[2])stats[2].textContent='محدثة'};
 let items=mergeScholarships([]).filter(x=>x.publishStatus==='published').sort((a,b)=>(a.sortOrder??999)-(b.sortOrder??999));paintStats(items);
 if(!document.querySelector('link[data-home-scholarships]')){const l=document.createElement('link');l.rel='stylesheet';l.href='homepage-scholarships.css?v=2';l.dataset.homeScholarships='';document.head.appendChild(l)}
 const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),theme=c=>c==='روسيا'?'ru':c==='المجر'?'hu':c==='تركيا'?'tr':'global';const cards=document.querySelector('.featured .cards');
 const renderCards=()=>{const featured=items.filter(x=>x.featured).slice(0,3),chosen=featured.length>=3?featured:items.slice(0,3);if(cards&&chosen.length)cards.innerHTML=chosen.map(s=>{const href=`scholarship.html?slug=${encodeURIComponent(s.slug||s.id)}`,levels=(s.studyLevels||[]).slice(0,3).join(' • ');return `<article class="card home-scholarship theme-${theme(s.country)}"><div class="cover"><div class="cover-glow"></div><div><small>${esc(s.country||'دولي')}</small><h3>${esc(s.title||'منحة')}</h3><span>${esc(s.provider||'جهة مانحة')}</span></div></div><div class="body"><div class="pills"><span class="pill">${esc(s.statusLabel||'راجع الحالة')}</span><span class="pill gold">${esc(s.funding||'حسب البرنامج')}</span></div><p>${esc(s.shortDescription||'')}</p>${levels?`<div class="home-levels">${esc(levels)}</div>`:''}<div class="bottom"><div>موعد الإغلاق<br><b>${esc(s.deadline||'حسب الجهة')}</b></div><a class="detail" href="${href}">عرض المنحة</a></div></div></article>`}).join('')};renderCards();
 const refresh=async()=>{try{const app=getApps().length?getApp():initializeApp(firebaseConfig),db=getFirestore(app),snap=await getDocs(query(collection(db,'scholarships'),where('publishStatus','==','published'))),remote=snap.docs.map(d=>({id:d.id,...d.data()}));if(remote.length){items=mergeScholarships(remote).filter(x=>x.publishStatus==='published').sort((a,b)=>(a.sortOrder??999)-(b.sortOrder??999));paintStats(items);renderCards()}}catch(e){console.warn('Homepage remote data unavailable; using verified catalog.',e)}};('requestIdleCallback'in window?requestIdleCallback(refresh,{timeout:2200}):setTimeout(refresh,900));
}
