import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';import{collection,getDocs,getFirestore,query,where}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';import{firebaseConfig}from'./firebase-config.js';import{mergeScholarships}from'./scholarship-catalog.js';
if(location.pathname.endsWith('/')||location.pathname.endsWith('/index.html')){
 document.querySelector('.hero .cta [data-guest-only][href="register.html"]')?.remove();
 const cta=document.querySelector('.hero .cta');if(cta&&!cta.querySelector('[data-social-placeholder]')){const tg=document.createElement('button'),yt=document.createElement('button');tg.type=yt.type='button';tg.dataset.socialPlaceholder=yt.dataset.socialPlaceholder='1';tg.className='btn social-cta telegram';yt.className='btn social-cta youtube';tg.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 4 3.8 10.6c-1.2.5-1.2 1.2-.2 1.5l4.4 1.4 1.7 5.3c.2.7.1 1 .9 1 .6 0 .9-.3 1.2-.6l2.1-2.1 4.4 3.2c.8.5 1.4.2 1.6-.8L22.7 5c.3-1.1-.4-1.6-1.7-1Z"/></svg><span>تيليجرام</span>';yt.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M22 12s0-3.5-.4-5.2c-.2-.9-.9-1.6-1.8-1.8C18.1 4.5 12 4.5 12 4.5s-6.1 0-7.8.5c-.9.2-1.6.9-1.8 1.8C2 8.5 2 12 2 12s0 3.5.4 5.2c.2.9.9 1.6 1.8 1.8 1.7.5 7.8.5 7.8.5s6.1 0 7.8-.5c.9-.2 1.6-.9 1.8-1.8.4-1.7.4-5.2.4-5.2Zm-12.1 3.3V8.7L15.7 12l-5.8 3.3Z"/></svg><span>يوتيوب</span>';tg.title='سيتم ربط قناة تيليجرام قريبًا';yt.title='سيتم ربط قناة يوتيوب قريبًا';cta.append(tg,yt);if(!document.querySelector('#home-social-style')){const s=document.createElement('style');s.id='home-social-style';s.textContent='.hero .cta{flex-wrap:wrap}.social-cta{gap:8px;border:1px solid #d6ccbb;background:#fffaf2;color:#17352b;cursor:default}.social-cta svg{width:19px;height:19px;fill:currentColor}.social-cta.telegram{color:#247da8}.social-cta.youtube{color:#b42318}@media(max-width:520px){.hero .cta{display:grid;grid-template-columns:1fr 1fr}.hero .cta .primary{grid-column:1/-1}.social-cta{padding:11px 12px}}';document.head.appendChild(s)}}
 const stats=document.querySelectorAll('.stats .stat b');const paintStats=items=>{const countries=new Set(items.map(x=>x.country).filter(Boolean));if(stats[0])stats[0].textContent=items.length.toLocaleString('ar');if(stats[1])stats[1].textContent=countries.size.toLocaleString('ar');if(stats[2])stats[2].textContent='محدثة'};
 let items=mergeScholarships([]).filter(x=>x.publishStatus==='published').sort((a,b)=>(a.sortOrder??999)-(b.sortOrder??999));paintStats(items);
 if(!document.querySelector('link[data-home-scholarships]')){const l=document.createElement('link');l.rel='stylesheet';l.href='homepage-scholarships.css?v=2';l.dataset.homeScholarships='';document.head.appendChild(l)}
 const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c])),theme=c=>c==='روسيا'?'ru':c==='المجر'?'hu':c==='تركيا'?'tr':'global';const cards=document.querySelector('.featured .cards');
 const renderCards=()=>{const featured=items.filter(x=>x.featured).slice(0,3),chosen=featured.length>=3?featured:items.slice(0,3);if(cards&&chosen.length)cards.innerHTML=chosen.map(s=>{const href=`scholarship.html?slug=${encodeURIComponent(s.slug||s.id)}`,levels=(s.studyLevels||[]).slice(0,3).join(' • ');return `<article class="card home-scholarship theme-${theme(s.country)}"><div class="cover"><div class="cover-glow"></div><div><small>${esc(s.country||'دولي')}</small><h3>${esc(s.title||'منحة')}</h3><span>${esc(s.provider||'جهة مانحة')}</span></div></div><div class="body"><div class="pills"><span class="pill">${esc(s.statusLabel||'راجع الحالة')}</span><span class="pill gold">${esc(s.funding||'حسب البرنامج')}</span></div><p>${esc(s.shortDescription||'')}</p>${levels?`<div class="home-levels">${esc(levels)}</div>`:''}<div class="bottom"><div>موعد الإغلاق<br><b>${esc(s.deadline||'حسب الجهة')}</b></div><a class="detail" href="${href}">عرض المنحة</a></div></div></article>`}).join('')};renderCards();
 requestAnimationFrame(async()=>{try{const app=getApps().length?getApp():initializeApp(firebaseConfig),db=getFirestore(app),snap=await getDocs(query(collection(db,'scholarships'),where('publishStatus','==','published'))),remote=snap.docs.map(d=>({id:d.id,...d.data()}));if(remote.length){items=mergeScholarships(remote).filter(x=>x.publishStatus==='published').sort((a,b)=>(a.sortOrder??999)-(b.sortOrder??999));paintStats(items);renderCards()}}catch(e){console.warn('Homepage remote data unavailable; using verified catalog.',e)}});
}
