import{downloadNodePdf,getArtifact,safeFilename,saveArtifact,waitForUser}from'./student-artifacts.js?v=1';

const $=id=>document.getElementById(id);
const fields=['artifactName','name','current','program','target','whyField','whyProgram','future','achievements','lang','tone','template','manualText'];
const templates=[['academic','أكاديمي'],['formal','رسمي'],['minimal','Minimal'],['navy','Navy'],['elegant','Elegant'],['classic','Classic'],['modern','Modern'],['emerald','Emerald'],['serif','Serif'],['clean','Clean']];
let mode='auto',certificates=[],groupId=crypto.randomUUID(),version=1,lastSavedFingerprint='',saving=false;
const localKey='shadrat-motivation-v2';
const clean=v=>String(v||'').trim();
const safeHtml=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fingerprint=data=>JSON.stringify({data,mode,certificates});
const status=(text,type='')=>{const el=$('builderStatus');if(!el)return;el.textContent=text;el.className=`builder-status ${type}`.trim()};
const loadScript=(src,test)=>new Promise((resolve,reject)=>{if(test?.())return resolve();const old=[...document.scripts].find(s=>s.src===src);if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src=src;s.async=true;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});
async function ensurePdfJs(){await loadScript('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js',()=>!!window.pdfjsLib);window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'}
async function ensureOcr(){await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js',()=>!!window.Tesseract)}
async function ocr(source){await ensureOcr();const result=await window.Tesseract.recognize(source,'eng+ara',{logger:m=>{if(m.status==='recognizing text'&&Number.isFinite(m.progress))status(`جاري قراءة الشهادة… ${Math.round(m.progress*100)}%`)}});return result?.data?.text||''}
async function pdfText(file){await ensurePdfJs();const pdf=await window.pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let text='';const pages=Math.min(pdf.numPages,3);for(let i=1;i<=pages;i++){const page=await pdf.getPage(i),tc=await page.getTextContent(),direct=tc.items.map(x=>x.str).join('\n').trim();if(direct.length>60){text+='\n'+direct;continue}const viewport=page.getViewport({scale:1.45}),canvas=document.createElement('canvas');canvas.width=Math.round(viewport.width);canvas.height=Math.round(viewport.height);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;text+='\n'+await ocr(canvas)}return text.trim()}
async function readFile(file){if(file.type==='application/pdf'||/\.pdf$/i.test(file.name))return pdfText(file);if(file.type.startsWith('image/')||/\.(png|jpe?g|webp)$/i.test(file.name))return ocr(file);throw new Error('UNSUPPORTED')}
function extractInfo(raw){
  const normalized=String(raw||'').replace(/\r/g,'\n').replace(/[ \t]+/g,' ').trim();
  const lines=normalized.split(/\n+/).map(x=>x.trim()).filter(x=>x.length>=3&&x.length<=220);
  if(!lines.length)return null;
  const titleWords=/certificate|certification|achievement|completion|award|diploma|شهادة|إتمام|إنجاز|دبلوم|إفادة/i;
  const courseWords=/course|program|specialization|training|olympiad|competition|cyber|security|data|python|network|cloud|artificial|machine|دورة|برنامج|تخصص|مسابقة|أولمبياد|أمن|سيبر|بيانات|برمج|شبكات|ذكاء/i;
  const issuerWords=/university|academy|institute|foundation|school|college|coursera|google|microsoft|cisco|ibm|aws|oracle|جامعة|أكاديمية|معهد|مؤسسة|مدرسة|كلية/i;
  const personNoise=/awarded to|presented to|this is to certify|has successfully|تشهد|منحت إلى|مقدمة إلى|أتم بنجاح/i;
  const title=lines.find(x=>titleWords.test(x)&&!personNoise.test(x))||lines.find(x=>courseWords.test(x))||lines[0];
  const course=lines.find(x=>x!==title&&courseWords.test(x)&&!personNoise.test(x))||(/certificate|شهادة/i.test(title)?'':title);
  const issuer=lines.find(x=>x!==title&&x!==course&&issuerWords.test(x))||'';
  const dateMatch=normalized.match(/(?:\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+\d{1,2},?\s+\d{4}\b|\b\d{1,2}[\/.\-]\d{1,2}[\/.\-]\d{2,4}\b|\b\d{4}[\/.\-]\d{1,2}[\/.\-]\d{1,2}\b|\b\d{4}\b)/i);
  const taxonomy=[['Cybersecurity',/cyber|security|information security|أمن سيبر|الأمن السيبر|أمن المعلومات/i],['Networking',/network|tcp|routing|switching|شبكات/i],['Python',/python|بايثون/i],['Data Analysis',/data analysis|analytics|تحليل البيانات/i],['Artificial Intelligence',/artificial intelligence|machine learning|\bai\b|ذكاء اصطناعي|تعلم آلي/i],['Cloud',/cloud|aws|azure|gcp|سحاب/i],['Programming',/programming|software|coding|برمج|تطوير برمج/i],['Research',/research|بحث/i],['Leadership',/leadership|قيادة/i],['English',/english|ielts|toefl|إنجليزي|اللغة الإنجليزية/i],['Project Management',/project management|إدارة المشاريع/i]];
  const skills=taxonomy.filter(([,re])=>re.test(normalized)).map(([name])=>name);
  return{title:title||'',issuer,course:course||'',date:dateMatch?.[0]||'',skills,excerpt:lines.slice(0,8).join(' | ').slice(0,850)};
}
function certSummary(info){if(!info)return'';const pieces=[info.title,info.course&&info.course!==info.title?info.course:'',info.issuer?`— ${info.issuer}`:'',info.date?`(${info.date})`:'',info.skills?.length?`— ${info.skills.join(', ')}`:''];return pieces.filter(Boolean).join(' ')}
function renderCerts(){const box=$('certResults');if(!box)return;if(!certificates.length){box.innerHTML='';return}box.innerHTML=certificates.map((c,i)=>c.error?`<div class="cert-result error"><b>${safeHtml(c.fileName)}</b><span>تعذر استخراج بيانات موثوقة من هذه الشهادة.</span><small>يمكنك المحاولة بصورة أوضح أو PDF يحتوي نصًا.</small></div>`:`<div class="cert-result"><b>${safeHtml(c.info.title||'شهادة')}</b><span>${safeHtml([c.info.course,c.info.issuer].filter(Boolean).join(' — ')||'تم استخراج النص')}</span><small>${safeHtml([c.info.date,c.info.skills?.join(', ')].filter(Boolean).join(' · '))}</small></div>`).join('')}
function syncAchievements(){const extracted=certificates.filter(c=>!c.error&&c.info).map(c=>certSummary(c.info)).filter(Boolean);const existing=clean($('achievements').value).split(/\n+/).filter(Boolean).filter(x=>!x.startsWith('[مستخرج] '));const merged=[...existing,...extracted.map(x=>'[مستخرج] '+x)];$('achievements').value=merged.join('\n');renderDraft()}
function collect(){return Object.fromEntries(fields.map(id=>[id,$(id)?.value||'']))}
function evidenceLines(){return clean($('achievements').value).split(/\n+/).map(x=>x.replace(/^\[مستخرج\]\s*/,'').trim()).filter(Boolean).slice(0,8)}
function autoEnglish(){
  const name=clean($('name').value),current=clean($('current').value),program=clean($('program').value),target=clean($('target').value),whyField=clean($('whyField').value),whyProgram=clean($('whyProgram').value),future=clean($('future').value),evidence=evidenceLines();
  if(!name||!program||!target)throw new Error('REQUIRED');
  const parts=[`Dear Admissions Committee,`,`I am writing to apply for ${program} and to pursue further study in ${target}.${current?` My current academic background as ${current} has strengthened my determination to continue developing in this direction.`:''}`];
  if(whyField)parts.push(whyField);
  if(evidence.length)parts.push(`My preparation is supported by experiences and achievements including ${evidence.join('; ')}. I value these experiences because they reflect consistent effort and continued learning relevant to my intended path.`);
  if(whyProgram)parts.push(whyProgram);else parts.push(`I see ${program} as an opportunity to deepen my academic preparation in ${target}, learn in a structured environment, and turn my existing motivation into stronger knowledge and practical capability.`);
  if(future)parts.push(future);
  parts.push(`I am prepared to approach this opportunity with discipline, responsibility, and a willingness to learn. Thank you for considering my application.`,`Sincerely,\n${name}`);return parts.join('\n\n')
}
function autoArabic(){
  const name=clean($('name').value),current=clean($('current').value),program=clean($('program').value),target=clean($('target').value),whyField=clean($('whyField').value),whyProgram=clean($('whyProgram').value),future=clean($('future').value),evidence=evidenceLines();
  if(!name||!program||!target)throw new Error('REQUIRED');
  const parts=[`السادة لجنة القبول المحترمون،`,`أتقدم بطلب الالتحاق بـ ${program} لمواصلة دراستي في مجال ${target}.${current?` وتدعم خلفيتي الحالية بصفتي ${current} رغبتي في تطوير نفسي بصورة أعمق في هذا المسار.`:''}`];
  if(whyField)parts.push(whyField);
  if(evidence.length)parts.push(`ويستند استعدادي إلى عدد من الخبرات والإنجازات، من بينها: ${evidence.join('؛ ')}. وتمثل هذه التجارب بالنسبة لي دليلًا على الاستمرار في التعلم والعمل الجاد في المجالات المرتبطة بمساري المستهدف.`);
  if(whyProgram)parts.push(whyProgram);else parts.push(`أرى أن ${program} فرصة مناسبة لتعميق استعدادي الأكاديمي في ${target} والتعلم ضمن بيئة منظمة تساعدني على تحويل الدافع الحالي إلى معرفة وخبرة أقوى.`);
  if(future)parts.push(future);
  parts.push(`سأتعامل مع هذه الفرصة بالجدية والمسؤولية والاستعداد المستمر للتعلم. أشكركم على وقتكم واهتمامكم بطلب التقديم.`,`مع خالص التقدير،\n${name}`);return parts.join('\n\n')
}
function updatePreview(text){$('letterText').textContent=text||'أدخل معلوماتك ثم اضغط «تجهيز الخطاب».';$('letter').dir=$('lang').value==='ar'?'rtl':'ltr';$('letter').className=`letter letter-template-${$('template').value||'academic'}`;$('letterTitle').textContent=$('lang').value==='ar'?'خطاب الدافع':'Motivation Letter';$('letterMeta').textContent=[clean($('name').value),clean($('program').value),clean($('target').value)].filter(Boolean).join(' · ');$('counter').textContent=text?`${text.trim().split(/\s+/).length} كلمة`:'';document.querySelectorAll('[data-motivation-template]').forEach(btn=>btn.classList.toggle('is-active',btn.dataset.motivationTemplate===$('template').value))}
function generate(){try{const text=mode==='manual'?clean($('manualText').value):($('lang').value==='ar'?autoArabic():autoEnglish());if(mode==='manual'&&!text){status('اكتب نص الخطاب في الوضع اليدوي.','error');return''}updatePreview(text);saveLocal();status('تم تجهيز الخطاب من المعلومات المدخلة.','success');return text}catch(error){if(error.message==='REQUIRED')status('للتوليد التلقائي اكتب الاسم، البرنامج/المنحة، والتخصص المستهدف على الأقل.','error');else{console.error(error);status('تعذر تجهيز الخطاب.','error')}return''}}
function setMode(next){mode=next==='manual'?'manual':'auto';document.querySelectorAll('[data-letter-mode]').forEach(b=>b.classList.toggle('is-active',b.dataset.letterMode===mode));$('autoFields').hidden=mode==='manual';$('manualFields').hidden=mode!=='manual';saveLocal();if(mode==='manual')updatePreview(clean($('manualText').value))}
function saveLocal(){try{localStorage.setItem(localKey,JSON.stringify({groupId,version,mode,data:collect(),certificates}))}catch{}}
function setupTemplates(){const box=$('templatePicker');box.innerHTML=templates.map(([v,l])=>`<button type="button" class="template-choice" data-motivation-template="${v}">${l}</button>`).join('');box.onclick=e=>{const b=e.target.closest('[data-motivation-template]');if(!b)return;$('template').value=b.dataset.motivationTemplate;updatePreview($('letterText').textContent);saveLocal()}}
async function saveCloud({silent=false}={}){if(saving)return null;const text=generate();if(!text)return null;const data=collect();if(!clean(data.artifactName))data.artifactName='Motivation 1';const user=await waitForUser();if(!user){if(!silent)status('سجّل الدخول أولًا ليُحفظ الخطاب في حسابك.','error');return null}saving=true;if(!silent)status('جارٍ حفظ الخطاب في حسابك…');try{const saved=await saveArtifact({artifactType:'motivation',artifactGroupId:groupId,artifactName:data.artifactName,studentName:data.name,specialization:data.target,program:data.program,template:data.template,language:data.lang,version,data:{...data,mode},renderedHtml:$('letter').outerHTML,renderedText:text,certificateSummaries:certificates.filter(c=>!c.error).map(c=>c.info)});lastSavedFingerprint=fingerprint(data);version+=1;saveLocal();if(!silent)status(`تم الحفظ باسم «${data.artifactName}».`,'success');return saved}catch(error){console.error(error);if(!silent)status('تعذر حفظ الخطاب الآن.','error');return null}finally{saving=false}}
async function download(){const text=generate();if(!text)return;const data=collect(),btn=$('downloadBtn'),old=btn.textContent;btn.disabled=true;btn.textContent='جاري تجهيز PDF…';try{const user=await waitForUser(1200);if(user&&fingerprint(data)!==lastSavedFingerprint)await saveCloud({silent:true});await downloadNodePdf($('letter'),`${safeFilename(data.name||'Student')}-Motivation-Letter.pdf`);status('تم تجهيز ملف PDF.','success')}catch(error){console.error(error);status('تعذر تجهيز PDF على هذا المتصفح. أعد المحاولة في Safari أو Chrome.','error')}finally{btn.disabled=false;btn.textContent=old}}
async function handleCertificates(files){certificates=[];$('certResults').innerHTML=[...files].map(f=>`<div class="cert-result"><b>${safeHtml(f.name)}</b><small>جاري القراءة…</small></div>`).join('');let i=0;for(const file of files){try{status(`جاري قراءة الشهادة ${i+1} من ${files.length}…`);const raw=await readFile(file),info=extractInfo(raw);if(!info)throw new Error('NO_TEXT');certificates.push({fileName:file.name,info})}catch(error){console.warn('[Shadrat] certificate extraction failed',file.name,error);certificates.push({fileName:file.name,error:true})}i++;renderCerts()}syncAchievements();status('اكتملت قراءة الشهادات. راجع البيانات المستخرجة قبل التقديم.','success');saveLocal()}
function renderDraft(){saveLocal();if(mode==='manual')updatePreview(clean($('manualText').value))}
async function loadInitial(){setupTemplates();const params=new URLSearchParams(location.search),artifactId=params.get('artifact');if(artifactId){try{const a=await getArtifact(artifactId);if(a?.artifactType==='motivation'){groupId=a.artifactGroupId||groupId;version=Number(a.version||1)+1;const d=a.data||{};fields.forEach(id=>{if($(id)&&d[id]!=null)$(id).value=d[id]});mode=d.mode||'auto';certificates=(a.certificateSummaries||[]).map(info=>({fileName:'شهادة محفوظة',info}));setMode(mode);renderCerts();updatePreview(a.renderedText||'');lastSavedFingerprint=fingerprint(collect());status('تم تحميل النسخة المحفوظة.','success');return}}catch(error){console.warn(error)}}try{const s=JSON.parse(localStorage.getItem(localKey)||'null');if(s?.data){groupId=s.groupId||groupId;version=Number(s.version||1);fields.forEach(id=>{if($(id)&&s.data[id]!=null)$(id).value=s.data[id]});mode=s.mode||'auto';certificates=s.certificates||[];setMode(mode);renderCerts();if(mode==='manual')updatePreview(clean($('manualText').value));return}}catch{}const user=await waitForUser(900);if(user&&!$('name').value)$('name').value=user.displayName||'';setMode('auto');updatePreview('')}
fields.forEach(id=>$(id)?.addEventListener('input',renderDraft));document.querySelectorAll('[data-letter-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.letterMode)));$('generateBtn')?.addEventListener('click',generate);$('saveBtn')?.addEventListener('click',()=>saveCloud());$('downloadBtn')?.addEventListener('click',download);$('copyBtn')?.addEventListener('click',async()=>{const text=$('letterText').textContent;if(!text)return;await navigator.clipboard.writeText(text);const b=$('copyBtn'),old=b.textContent;b.textContent='تم النسخ ✓';setTimeout(()=>b.textContent=old,1200)});$('certFiles')?.addEventListener('change',e=>handleCertificates([...e.target.files]));
loadInitial();
