import{downloadNodePdf,getArtifact,safeFilename,saveArtifact,waitForUser}from'./student-artifacts-a4.js?v=3';
import{compactCertificate,readCertificate,skillLabels}from'./certificate-reader.js?v=1';

const $=id=>document.getElementById(id);
const fields=['artifactName','name','current','program','target','whyField','whyProgram','future','achievements','lang','tone','template','manualText'];
const templates=[
  {id:'academic',label:'أكاديمي',desc:'جامعة وكلاسيكي'},
  {id:'formal',label:'رسمي',desc:'مراسلات رسمية'},
  {id:'editorial',label:'صحيفة',desc:'Editorial مميز'},
  {id:'modern',label:'حديث',desc:'هيدر عصري'},
  {id:'executive',label:'تنفيذي',desc:'Letterhead داكن'},
  {id:'minimal',label:'Minimal',desc:'هوامش واسعة وبسيط'},
  {id:'creative',label:'إبداعي',desc:'بطاقة وهوية واضحة'},
  {id:'technical',label:'تقني',desc:'منظم ومناسب للتقنية'},
  {id:'serif',label:'Serif',desc:'تحريري أنيق'},
  {id:'clean',label:'Clean',desc:'خط جانبي ونظيف'}
];
let mode='auto',certificates=[],groupId=crypto.randomUUID(),version=1,lastSavedFingerprint='',saving=false,liveTimer=null;
const localKey='shadrat-motivation-v3';
const clean=v=>String(v||'').trim();
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines=v=>String(v||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);
const fingerprint=data=>JSON.stringify({data,mode,certificates:certificates.map(c=>c.info||{fileName:c.fileName,error:true})});
const status=(text,type='')=>{const el=$('builderStatus');if(!el)return;el.textContent=text;el.className=`builder-status ${type}`.trim()};
function collect(){return Object.fromEntries(fields.map(id=>[id,$(id)?.value||'']))}
function normalizeTemplate(value){const map={navy:'executive',elegant:'creative',classic:'formal',emerald:'modern'};return templates.some(t=>t.id===value)?value:(map[value]||'academic')}
function certificateParagraph(info,lang,target){if(!info)return'';const course=info.course||info.title||'',issuer=info.issuer||'',date=info.date||'',skills=skillLabels(info,lang),skillText=skills.join(lang==='ar'?'، ':', ');if(lang==='ar'){
  const first=course?`ومن العناصر الموثقة في ملفي شهادة «${course}»${issuer?` الصادرة من ${issuer}`:''}${date?` بتاريخ ${date}`:''}.`:`ومن العناصر الموثقة في ملفي شهادة${issuer?` صادرة من ${issuer}`:''}${date?` بتاريخ ${date}`:''}.`;
  const second=skillText?`وتشير البيانات المستخرجة من الشهادة إلى محتوى مرتبط بـ ${skillText}.`:`وأدرج هذه الشهادة كما ظهرت بياناتها في الملف المرفق دون إضافة مهارات لم تذكر فيها.`;
  const third=target&&skillText?`ويخدم هذا التعلم مساري نحو ${target} في الجوانب التي يتقاطع فيها محتوى الشهادة مع المجال المستهدف.`:'وأعتبر هذا الإنجاز جزءًا من سجل تعلمي الموثق الذي أريد البناء عليه في المرحلة الأكاديمية القادمة.';
  return`${first} ${second} ${third}`;
 }
 const first=course?`One documented part of my preparation is the certificate “${course}”${issuer?` issued by ${issuer}`:''}${date?` on ${date}`:''}.`:`One documented part of my preparation is an uploaded certificate${issuer?` issued by ${issuer}`:''}${date?` on ${date}`:''}.`;
 const second=skillText?`The extracted certificate text is connected to ${skillText}.`:`I include this certificate exactly as documented, without adding skills that are not stated in the file.`;
 const third=target&&skillText?`This learning is relevant to my intended path in ${target} where the documented subject matter overlaps with that field.`:'I regard it as part of the documented learning record that I want to build on in my next academic stage.';
 return`${first} ${second} ${third}`;
}
function evidenceParagraphs(lang,target){const certs=certificates.filter(c=>!c.error&&c.info).slice(0,5).map(c=>certificateParagraph(c.info,lang,target));const achievements=lines($('achievements').value).slice(0,5).map(item=>lang==='ar'?`كما أدرج ضمن ملفي الإنجاز التالي كما هو موثق أو مدخل: ${item}. أتعامل معه كجزء من سجل التطور الذي يدعم استمراري في التعلم دون المبالغة في دلالته.`:`I also include the following achievement as documented or entered in my profile: ${item}. I treat it as part of a continuing record of development rather than as a substitute for further study.`);return[...certs,...achievements]}
function buildEnglish(){
  const name=clean($('name').value),current=clean($('current').value),program=clean($('program').value),target=clean($('target').value),whyField=clean($('whyField').value),whyProgram=clean($('whyProgram').value),future=clean($('future').value),tone=$('tone').value;
  if(!name||!target)throw new Error('REQUIRED');const programName=program||'this academic opportunity',evidence=evidenceParagraphs('en',target);
  const parts=['Dear Admissions Committee,'];
  parts.push(`I am writing to express my interest in ${programName} and to continue developing academically in ${target}.${current?` My current background as ${current} gives me a clear starting point from which I want to build a more focused and mature academic path.`:' I see this next stage as an opportunity to turn my present interest into a clearer, more structured, and more disciplined academic direction.'}`);
  parts.push(whyField?`${whyField} This reason matters to me because I want my next stage of study to be purposeful and connected to a field I am willing to explore in depth.`:`My interest in ${target} is based on a desire to understand the field more deeply, strengthen the foundations required for advanced study, and develop the ability to connect theory with responsible practical work. I am looking for sustained learning rather than a short-term result, and I want to improve through structured study, feedback, and repeated practice.`);
  parts.push(current?`My present background has also taught me the value of steady preparation. I want to build on what I have already studied, identify the areas that still require improvement, and approach new material with consistency. For me, academic progress means being able to explain what I know, recognize what I still need to learn, and keep developing that knowledge over time.`:`At this stage, I am focused on building a stronger academic foundation and improving the way I learn. I value clear goals, disciplined preparation, and the ability to learn from feedback. These are the habits I want to carry into a more demanding academic environment in ${target}.`);
  if(evidence.length)parts.push(...evidence);else parts.push(`I prefer to build my application around information I can actually document. Where I do not have a certificate or formal achievement to support a claim, I do not want to invent one. My objective is to keep strengthening my record through study, practice, and measurable progress.`);
  parts.push(whyProgram?`${whyProgram} This makes ${programName} particularly relevant to me because I am looking for an environment where I can develop with structure, clear expectations, and meaningful academic challenge.`:`I am interested in ${programName} because it represents a structured setting in which I can deepen my knowledge, improve the quality of my academic work, and learn under clear expectations. I am not assuming specific features that I have not verified; my motivation is centered on the opportunity to study seriously and progress within an organized academic framework.`);
  parts.push(future?`${future} I want the knowledge and discipline gained from this opportunity to become part of a long-term path rather than a short-term achievement.`:`Looking ahead, I want to use this opportunity to become better prepared for advanced study and professional development in ${target}. My goal is to leave the next stage with stronger knowledge, a clearer sense of direction, and a better ability to continue learning independently and responsibly.`);
  parts.push(tone==='personal'?`What matters most to me is genuine progress. I am ready to invest time and effort, learn from mistakes, revise my approach when necessary, and make serious use of the opportunities available to me.`:`I am prepared to approach this opportunity with discipline, responsibility, respect for academic standards, and a consistent willingness to learn, improve, and contribute constructively to the learning environment.`);
  parts.push(`Thank you for considering my application. I would be grateful for the opportunity to continue developing through ${programName} and to pursue my path in ${target} with seriousness and commitment.`,`Sincerely,\n${name}`);return parts.join('\n\n')
}
function buildArabic(){
  const name=clean($('name').value),current=clean($('current').value),program=clean($('program').value),target=clean($('target').value),whyField=clean($('whyField').value),whyProgram=clean($('whyProgram').value),future=clean($('future').value),tone=$('tone').value;
  if(!name||!target)throw new Error('REQUIRED');const programName=program||'هذه الفرصة الأكاديمية',evidence=evidenceParagraphs('ar',target);
  const parts=['السادة لجنة القبول المحترمون،'];
  parts.push(`أتقدم إليكم للتعبير عن اهتمامي بـ ${programName} ورغبتي في مواصلة التطور الأكاديمي في ${target}.${current?` وتمثل خلفيتي الحالية بصفتي ${current} نقطة بداية واضحة أريد أن أبني عليها مسارًا أكاديميًا أكثر تركيزًا ونضجًا.`:' وأرى أن المرحلة القادمة فرصة لتحويل اهتمامي الحالي إلى اتجاه دراسي أكثر وضوحًا وتنظيمًا وانضباطًا.'}`);
  parts.push(whyField?`${whyField} ويهمني هذا السبب لأنني أريد أن تكون المرحلة القادمة من دراستي هادفة ومرتبطة بمجال أستعد لفهمه والتعمق فيه بصورة حقيقية.`:`ينطلق اهتمامي بـ ${target} من رغبتي في فهم المجال بصورة أعمق، وتقوية الأساس المطلوب للدراسة المتقدمة، وتطوير قدرتي على الربط بين المعرفة النظرية والتطبيق المسؤول. ولا أبحث عن نتيجة مؤقتة، بل عن تعلم مستمر يقوم على الدراسة المنظمة والمراجعة والتطبيق المتدرج.`);
  parts.push(current?`كما علمتني خلفيتي الحالية أهمية الاستعداد المتدرج. أريد أن أبني على ما درسته بالفعل، وأن أحدد الجوانب التي ما زالت تحتاج إلى تطوير، وأن أتعامل مع المعرفة الجديدة باستمرارية. وبالنسبة لي فإن التقدم الأكاديمي يعني أن أستطيع توضيح ما أعرفه، وأن أدرك ما ينقصني، وأن أستمر في تطوير معرفتي بمرور الوقت.`:`أركز في هذه المرحلة على بناء أساس أكاديمي أقوى وتحسين طريقة تعلمي. وأهتم بوضوح الأهداف والانضباط في الاستعداد والاستفادة من الملاحظات، وهي عادات أريد أن أحملها معي إلى بيئة أكاديمية أكثر تطلبًا في ${target}.`);
  if(evidence.length)parts.push(...evidence);else parts.push(`أفضل أن أبني طلبي على معلومات أستطيع توثيقها فعليًا. وعندما لا توجد لدي شهادة أو إنجاز رسمي يدعم ادعاءً معينًا، فلا أريد أن أختلقه. هدفي هو تقوية سجلي تدريجيًا من خلال الدراسة والممارسة والتقدم القابل للقياس.`);
  parts.push(whyProgram?`${whyProgram} ولهذا تمثل ${programName} بالنسبة لي فرصة ذات صلة مباشرة بما أبحث عنه من بيئة منظمة وتوقعات واضحة وتحدٍ أكاديمي حقيقي.`:`أهتم بـ ${programName} لأنها تمثل إطارًا منظمًا يمكنني من خلاله تعميق معرفتي وتحسين جودة عملي الأكاديمي والتعلم ضمن توقعات واضحة. ولا أفترض مزايا محددة للبرنامج لم أتحقق منها؛ فدافعي الأساسي هو الدراسة الجادة والتقدم داخل بيئة أكاديمية منظمة.`);
  parts.push(future?`${future} وأريد أن تصبح المعرفة والانضباط اللذان أكتسبهما من هذه الفرصة جزءًا من مسار طويل المدى، لا إنجازًا مؤقتًا فقط.`:`وعلى المدى القادم، أريد أن تساعدني هذه المرحلة على الاستعداد بصورة أفضل للدراسة المتقدمة والتطور المهني في ${target}. وأطمح إلى الخروج منها بمعرفة أقوى واتجاه أوضح وقدرة أفضل على مواصلة التعلم بصورة مستقلة ومسؤولة.`);
  parts.push(tone==='personal'?`ما يهمني في النهاية هو التقدم الحقيقي. وأنا مستعد لبذل الوقت والجهد، والتعلم من الأخطاء، وتعديل طريقتي عند الحاجة، والاستفادة الجادة من الفرص التي تتاح لي.`:`أنا مستعد للتعامل مع هذه الفرصة بانضباط ومسؤولية واحترام للمعايير الأكاديمية، مع الاستمرار في التعلم والتحسن والمساهمة بصورة إيجابية في البيئة التعليمية.`);
  parts.push(`أشكركم على وقتكم واهتمامكم بطلب التقديم. وسأكون ممتنًا لفرصة مواصلة التطور من خلال ${programName} والاستمرار في مساري نحو ${target} بجدية والتزام.`,`مع خالص التقدير،\n${name}`);return parts.join('\n\n')
}
function buildText(){if(mode==='manual'){const text=clean($('manualText').value);if(!text)throw new Error('MANUAL_REQUIRED');return text}return $('lang').value==='ar'?buildArabic():buildEnglish()}
function updatePreview(text=''){const lang=$('lang').value==='ar'?'ar':'en',template=normalizeTemplate($('template').value);$('template').value=template;$('letterText').textContent=text||(lang==='ar'?'أدخل الاسم والتخصص ليظهر الخطاب هنا.':'Enter your name and target field to build the letter.');$('letter').dir=lang==='ar'?'rtl':'ltr';$('letter').className=`letter letter-template-${template}`;$('letterTitle').textContent=lang==='ar'?'خطاب الدافع':'Motivation Letter';$('letterMeta').textContent=[clean($('name').value),clean($('program').value),clean($('target').value)].filter(Boolean).join(' · ');$('counter').textContent=text?`${text.trim().split(/\s+/).length} ${lang==='ar'?'كلمة':'words'}`:'';document.querySelectorAll('[data-motivation-template]').forEach(btn=>btn.classList.toggle('is-active',btn.dataset.motivationTemplate===template))}
function renderCertificates(){const box=$('certResults');if(!box)return;if(!certificates.length){box.innerHTML='';return}const lang=$('lang').value==='ar'?'ar':'en';box.innerHTML=certificates.map((c,i)=>c.error?`<div class="cert-result error"><b>${esc(c.fileName)}</b><span>تعذر استخراج بيانات موثوقة من هذه الشهادة.</span><button type="button" class="cert-remove" data-remove-cert="${i}">حذف</button></div>`:`<div class="cert-result"><b>${esc(c.info.course||c.info.title||c.fileName)}</b><span>${esc([c.info.issuer,c.info.date].filter(Boolean).join(' · ')||'تم استخراج بيانات الشهادة')}</span><small>${esc(compactCertificate(c.info,lang))}</small><button type="button" class="cert-remove" data-remove-cert="${i}">حذف</button></div>`).join('');box.querySelectorAll('[data-remove-cert]').forEach(btn=>btn.onclick=()=>{certificates.splice(Number(btn.dataset.removeCert),1);renderCertificates();renderDraft();saveLocal()})}
function renderDraft(){renderCertificates();try{if(mode==='manual'){updatePreview(clean($('manualText').value));return}if(!clean($('name').value)||!clean($('target').value)){updatePreview('');return}updatePreview(buildText())}catch{updatePreview('')}saveLocal()}
function scheduleDraft(){clearTimeout(liveTimer);liveTimer=setTimeout(renderDraft,170)}
function generate({silent=false}={}){try{const text=buildText();updatePreview(text);saveLocal();if(!silent)status('تم تجهيز خطاب مفصل من المعلومات المتوفرة والشهادات المستخرجة فقط.','success');return text}catch(error){if(!silent){if(error.message==='REQUIRED')status('اكتب الاسم والتخصص المستهدف على الأقل. البرنامج/المنحة وبقية التفاصيل تزيد تخصيص الخطاب.','error');else if(error.message==='MANUAL_REQUIRED')status('اكتب نص الخطاب في الوضع اليدوي.','error');else{console.error(error);status('تعذر تجهيز الخطاب.','error')}}return''}}
function setMode(next){mode=next==='manual'?'manual':'auto';document.querySelectorAll('[data-letter-mode]').forEach(b=>b.classList.toggle('is-active',b.dataset.letterMode===mode));$('autoFields').hidden=mode==='manual';$('manualFields').hidden=mode!=='manual';renderDraft();saveLocal()}
function saveLocal(){try{localStorage.setItem(localKey,JSON.stringify({groupId,version,mode,data:collect(),certificates}))}catch{}}
function setupTemplates(){const box=$('templatePicker');if(!box)return;box.innerHTML=templates.map(t=>`<button type="button" class="template-choice template-choice-letter-${t.id}" data-motivation-template="${t.id}"><b>${t.label}</b><small>${t.desc}</small></button>`).join('');box.onclick=e=>{const b=e.target.closest('[data-motivation-template]');if(!b)return;$('template').value=b.dataset.motivationTemplate;renderDraft()}}
async function handleCertificates(files){const chosen=[...files].slice(0,12);for(const file of chosen){status(`جاري قراءة ${file.name}… 0%`);try{const result=await readCertificate(file,{onProgress:p=>status(`جاري قراءة ${file.name}… ${p}%`)});certificates.push(result);status(`تم استخراج بيانات ${file.name} واستخدامها في الخطاب.`,'success')}catch(error){console.error(error);certificates.push({fileName:file.name,error:true});status(`تعذر استخراج بيانات موثوقة من ${file.name}.`,'error')}renderDraft()}$('certFiles').value='';saveLocal()}
async function saveCloud({silent=false}={}){if(saving)return null;const text=generate({silent});if(!text)return null;const data=collect();if(!clean(data.artifactName))data.artifactName='Motivation 1';const user=await waitForUser();if(!user){if(!silent)status('سجّل الدخول أولًا ليُحفظ الخطاب في حسابك.','error');return null}saving=true;const button=$('saveBtn'),old=button?.textContent;if(button&&!silent){button.disabled=true;button.textContent='جاري الحفظ…'}if(!silent)status('جارٍ حفظ الخطاب في حسابك…');try{const saved=await saveArtifact({artifactType:'motivation',artifactGroupId:groupId,artifactName:data.artifactName,studentName:data.name,specialization:data.target,program:data.program,template:normalizeTemplate(data.template),language:data.lang,version,data:{...data,mode,certificates:certificates.map(c=>c.error?{fileName:c.fileName,error:true}:c.info)},renderedHtml:$('letter').outerHTML,renderedText:text,certificateSummaries:certificates.filter(c=>!c.error&&c.info).map(c=>c.info)});lastSavedFingerprint=fingerprint(data);version+=1;saveLocal();if(!silent)status(`تم حفظ «${data.artifactName}» ويمكن الرجوع إليه من حسابك.`,'success');return saved}catch(error){console.error(error);if(!silent)status('تعذر حفظ الخطاب الآن.','error');return null}finally{saving=false;if(button&&!silent){button.disabled=false;button.textContent=old||'حفظ في حسابي'}}}
async function download(){const text=generate();if(!text)return;const data=collect(),btn=$('downloadBtn'),old=btn.textContent;btn.disabled=true;btn.textContent='جاري تجهيز PDF…';try{const user=await waitForUser(1200);if(user&&fingerprint(data)!==lastSavedFingerprint)await saveCloud({silent:true});await downloadNodePdf($('letter'),`${safeFilename(data.name,'Student')}-Motivation-Letter.pdf`);status('تم تجهيز PDF من نفس صفحة A4 الظاهرة في المعاينة.','success')}catch(error){console.error(error);status('تعذر تجهيز PDF الآن. أعد المحاولة.','error')}finally{btn.disabled=false;btn.textContent=old}}
async function loadInitial(){setupTemplates();document.querySelectorAll('[data-letter-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.letterMode));const artifactId=new URLSearchParams(location.search).get('artifact');if(artifactId){try{const artifact=await getArtifact(artifactId);if(artifact?.artifactType==='motivation'){groupId=artifact.artifactGroupId||crypto.randomUUID();version=Number(artifact.version||1)+1;const data=artifact.data||{};fields.forEach(id=>{if($(id)&&data[id]!=null)$(id).value=data[id]});$('template').value=normalizeTemplate(data.template||artifact.template);mode=data.mode==='manual'?'manual':'auto';certificates=(artifact.certificateSummaries||data.certificates||[]).map(info=>info?.error?info:{fileName:info.fileName||'',info});$('artifactName').value=artifact.artifactName||$('artifactName').value;setMode(mode);lastSavedFingerprint=fingerprint(collect());status('تم تحميل النسخة المحفوظة. الحفظ القادم سيُنشئ نسخة جديدة.','success');return}}catch(error){console.warn(error)}}
  try{const saved=JSON.parse(localStorage.getItem(localKey)||'null');if(saved?.data){groupId=saved.groupId||groupId;version=Number(saved.version||1);mode=saved.mode==='manual'?'manual':'auto';certificates=saved.certificates||[];fields.forEach(id=>{if($(id)&&saved.data[id]!=null)$(id).value=saved.data[id]});$('template').value=normalizeTemplate($('template').value);setMode(mode);return}}catch{}
  const user=await waitForUser(900);if(user&&!$('name').value)$('name').value=user.displayName||'';$('template').value='academic';setMode('auto')}
fields.forEach(id=>$(id)?.addEventListener('input',scheduleDraft));$('certFiles')?.addEventListener('change',e=>handleCertificates(e.target.files));$('generateBtn')?.addEventListener('click',()=>generate());$('saveBtn')?.addEventListener('click',()=>saveCloud());$('downloadBtn')?.addEventListener('click',download);$('copyBtn')?.addEventListener('click',async()=>{const text=generate({silent:true})||clean($('letterText').textContent);if(!text)return;try{await navigator.clipboard.writeText(text);status('تم نسخ نص الخطاب.','success')}catch{status('تعذر النسخ التلقائي.','error')}});
loadInitial();
