import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{getAuth,onAuthStateChanged,signOut}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{doc,getDoc,getFirestore}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import{firebaseConfig}from'./firebase-config.js';
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),OWNER_EMAIL='shadrat.almn7@gmail.com',AUTH_SESSION_KEY='shadrat_auth_session';
function hasFreshAuthSession(user){try{const s=JSON.parse(sessionStorage.getItem(AUTH_SESSION_KEY)||'null');return s?.uid===user.uid&&Date.now()-Number(s.at||0)<=12*60*60*1000}catch{return false}}
const svg=p=>`<svg class="shadrat-nav-svg" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="${p}"/></svg>`,adminIcon=svg('M12 3.5 19 6v5.4c0 4.3-2.7 7.6-7 9.1-4.3-1.5-7-4.8-7-9.1V6l7-2.5Zm0 4v6m-3-3h6');
const adminIcons={overview:svg('M4 11.2 12 4l8 7.2v8.3H14.5v-5.5h-5V19.5H4v-8.3Z'),content:svg('M5 4h14v5H5V4Zm0 8h6v8H5v-8Zm9 0h5v8h-5v-8Z'),students:svg('M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM5 20c.7-3.6 3-5.5 7-5.5s6.3 1.9 7 5.5'),staff:svg('M8 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm8 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM3 20c.4-3.3 2.2-5 5-5 2.1 0 3.6.9 4.4 2.6M13 20c.3-2.7 1.5-4 3.5-4s3.2 1.3 3.5 4'),support:svg('M5 5h14v14H5V5Zm3 4h8M8 13h5M8 17h7'),gamification:svg('M12 3l2.3 4.7 5.2.8-3.8 3.7.9 5.3-4.6-2.5-4.6 2.5.9-5.3-3.8-3.7 5.2-.8L12 3Z'),system:svg('M12 3 19 6v5c0 4.6-2.7 7.8-7 10-4.3-2.2-7-5.4-7-10V6l7-3Zm-3 9 2 2 4-4')};
const adminEntries=[['admin-analytics.html','الرئيسية الإدارية','overview',['owner','admin','support','editor','communityModerator']],['admin-homepage.html','إدارة المحتوى','content',['owner','admin','editor']],['admin-users.html','الطلاب','students',['owner','admin','support']],['admin-staff.html','الموظفون','staff',['owner']],['admin-orders.html','الطلبات والدعم','support',['owner','admin','support']],['admin-gamification.html','XP والإشعارات','gamification',['owner','admin']],['admin-security.html','النظام والدخل','system',['owner','admin']]],allowedEntries=role=>adminEntries.filter(([, , ,roles])=>roles.includes(role));
const link=(href,label,key)=>`<a data-owner-link data-admin-section="${key}" href="${href}"><span class="admin-hamburger-icon menu-icon">${adminIcons[key]||adminIcon}</span><span class="admin-hamburger-label menu-label">${label}</span><b class="admin-count-badge" data-admin-badge="${key}" hidden>0</b></a>`;
const staffCard=role=>`<section class="hamburger-section owner-admin-section" data-admin-menu-card data-accordion="admin"><button type="button" class="hamburger-section-toggle" aria-expanded="false"><span><b>إدارة شذرات</b><small>لوحة المالك والإدارة</small></span><i aria-hidden="true">⌄</i></button><div class="hamburger-section-links" hidden>${allowedEntries(role).map(([href,label,key])=>link(href,label,key)).join('')}</div></section>`;
const aliases={'admin-scholarships.html':'admin-homepage.html','admin-services.html':'admin-homepage.html','admin-offers.html':'admin-homepage.html','admin-videos.html':'admin-homepage.html','admin-messages.html':'admin-orders.html','admin-announcements.html':'admin-gamification.html','admin-revenue.html':'admin-security.html'};
function markCurrent(){const current=location.pathname.split('/').pop()||'index.html',active=aliases[current]||current;document.querySelectorAll('[data-owner-link]').forEach(a=>{const on=a.getAttribute('href')===active;a.classList.toggle('is-current',on);if(on)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')})}
function wireInjectedAccordion(card){const button=card.querySelector('.hamburger-section-toggle'),links=card.querySelector('.hamburger-section-links');if(!button||!links)return;button.addEventListener('click',()=>{const open=button.getAttribute('aria-expanded')!=='true';card.classList.toggle('is-open',open);button.setAttribute('aria-expanded',String(open));links.hidden=!open})}
const logout=async()=>{await signOut(auth);location.replace('index.html')};
function addBack(){const page=location.pathname.split('/').pop()||'index.html';if(page==='index.html'||page.startsWith('admin-')||document.querySelector('[data-context-back]'))return;const scholarshipDetails=new Set(['scholarship.html','open-doors.html','education-in-russia.html','hse-scholarship.html','nsu-scholarship.html','rudn-scholarship.html','stipendium-hungaricum.html','turkiye-scholarships.html','scholarship-new.html']);let href='index.html',label='العودة إلى الرئيسية';if(scholarshipDetails.has(page)){href='scholarships.html';label='العودة إلى قائمة المنح'}else if(['university-shukhov.html','service-request.html','cv-builder.html','motivation-letter.html','documents.html'].includes(page)){href='services.html';label='العودة إلى الخدمات'}else if(page==='student-profile.html'){href='profile.html';label='العودة إلى حسابي'}const nav=document.querySelector('.site-header .nav');if(!nav)return;if(!document.getElementById('shadrat-back-style')){const style=document.createElement('style');style.id='shadrat-back-style';style.textContent='.site-back-button{width:40px;height:40px;flex:0 0 40px;display:inline-grid;place-items:center;border-radius:12px;border:1px solid rgba(37,99,235,.18);background:#fff;color:#2563eb;text-decoration:none;box-shadow:0 6px 18px rgba(15,23,42,.07)}.site-back-button svg{width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:2.2;stroke-linecap:round;stroke-linejoin:round}@media(max-width:820px){.site-header .nav{position:relative}.site-back-button{position:absolute;left:0;top:calc(100% + 9px);z-index:70}}';document.head.appendChild(style)}const a=document.createElement('a');a.href=href;a.className='site-back-button';a.dataset.contextBack='';a.setAttribute('aria-label',label);a.title=label;a.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 5l-7 7 7 7"/><path d="M8 12h11"/></svg>';const hamburger=nav.querySelector('.global-hamburger');if(hamburger)nav.insertBefore(a,hamburger);else nav.appendChild(a)}
function addLogout(){const root=document.querySelector('.hamburger-auth-mini')||document.querySelector('.hamburger-sections');if(!root||root.querySelector('[data-auth-logout]'))return;const b=document.createElement('button');b.type='button';b.dataset.authLogout='';b.textContent='تسجيل الخروج';b.addEventListener('click',logout);root.appendChild(b)}
addBack();
onAuthStateChanged(auth,async user=>{if(user&&!hasFreshAuthSession(user)){sessionStorage.removeItem(AUTH_SESSION_KEY);sessionStorage.removeItem('shadrat_admin_session');await signOut(auth).catch(()=>{});user=null}document.body.dataset.authReady='true';document.querySelectorAll('[data-guest-only]').forEach(el=>{el.hidden=!!user;if(user)el.style.setProperty('display','none','important');else el.style.removeProperty('display')});document.querySelectorAll('a[href="login.html"],a[href="register.html"]').forEach(a=>{a.hidden=!!user;if(user)a.style.setProperty('display','none','important');else a.style.removeProperty('display')});document.querySelectorAll('[data-auth-logout]').forEach(b=>b.remove());if(!user){document.body.dataset.role='student';return}let role=user.email===OWNER_EMAIL?'owner':'student';if(role!=='owner'){try{const snap=await getDoc(doc(db,'users',user.uid)),p=snap.data()||{};role=p.accountStatus==='active'?(p.role||'student'):'student'}catch{}}document.body.dataset.role=role;if(['owner','admin','support','editor','communityModerator'].includes(role)){const grouped=document.querySelector('.hamburger-sections');if(grouped&&!grouped.querySelector('[data-admin-menu-card]')){const temp=document.createElement('div');temp.innerHTML=staffCard(role);const card=temp.firstElementChild;grouped.appendChild(card);wireInjectedAccordion(card)}markCurrent()}if(role==='owner')import('./owner-inline-tools.js?v=2').catch(error=>console.warn('[Shadrat] owner tools',error));addLogout()});