import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{doc,getDoc,getFirestore}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import{firebaseConfig}from'./firebase-config.js';
const OWNER_EMAIL='shadrat.almn7@gmail.com';
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const esc=v=>String(v??'');
function selectTab(id){document.querySelectorAll('[data-profile-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.profileTab===id));document.querySelectorAll('[data-profile-panel]').forEach(p=>p.classList.toggle('is-active',p.dataset.profilePanel===id));}
document.querySelectorAll('[data-profile-tab]').forEach(b=>b.addEventListener('click',()=>selectTab(b.dataset.profileTab)));
function ownerMode(){
 document.body.dataset.profileMode='owner';
 const tabs=document.querySelector('.profile-tabs');if(tabs)tabs.innerHTML=`<a class="owner-profile-link is-active" href="profile.html">ملف المالك</a><a class="owner-profile-link" href="admin-analytics.html">لوحة الإدارة</a><a class="owner-profile-link" href="admin-users.html">إدارة الطلاب</a><a class="owner-profile-link" href="admin-homepage.html">إدارة المحتوى</a><a class="owner-profile-link" href="admin-community.html">إدارة المجتمع</a>`;
 document.querySelectorAll('[data-profile-panel="level"],[data-profile-panel="rewards"],[data-profile-panel="orders"],[data-profile-panel="support"],#missions,#level,#rewards,#orders').forEach(el=>el.remove());
 const first=document.querySelector('[data-profile-panel="student-info"]');if(first){first.classList.add('is-active');first.querySelector('h2').textContent='معلومات المالك';}
 const grid=document.querySelector('.container.grid');if(grid&&!document.querySelector('#owner-shortcuts')){const s=document.createElement('section');s.className='card';s.id='owner-shortcuts';s.innerHTML=`<div class="card-heading"><div><span class="eyebrow">صلاحيات المالك</span><h2>اختصارات الإدارة</h2></div></div><div class="owner-shortcuts-grid"><a href="admin-analytics.html"><b>لوحة الإدارة</b><small>الإحصائيات والتنبيهات العامة</small></a><a href="admin-users.html"><b>الطلاب</b><small>الحسابات والأدوار والحالات</small></a><a href="admin-homepage.html"><b>المحتوى</b><small>المنح والخدمات والعروض</small></a><a href="admin-community.html"><b>المجتمع</b><small>المنشورات والإشراف والبلاغات</small></a><a href="admin-orders.html"><b>الطلبات والدعم</b><small>طلبات الخدمات ورسائل الطلاب</small></a><a href="admin-security.html"><b>النظام والدخل</b><small>الأمان والإعدادات والإيرادات</small></a></div>`;grid.appendChild(s)}
 const style=document.createElement('style');style.textContent=`body[data-profile-mode="owner"] .profile-progress{display:none}.owner-profile-link{display:flex;align-items:center;white-space:nowrap;border:1px solid var(--line);border-radius:99px;background:#fff;padding:9px 13px;font-weight:900;color:var(--ink)}.owner-profile-link.is-active{background:var(--green);color:#fff}.owner-shortcuts-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.owner-shortcuts-grid a{display:block;padding:16px;border:1px solid var(--line);border-radius:16px;background:#fff;color:var(--ink)}.owner-shortcuts-grid a:hover{border-color:#176b4b;background:#edf6f1}.owner-shortcuts-grid b,.owner-shortcuts-grid small{display:block}.owner-shortcuts-grid small{margin-top:5px;color:var(--muted)}@media(max-width:760px){.owner-shortcuts-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
}
onAuthStateChanged(auth,async user=>{if(!user){location.replace('login.html');return}let data={};try{const s=await getDoc(doc(db,'users',user.uid));data=s.data()||{}}catch{}const owner=(user.email||'').toLowerCase()===OWNER_EMAIL;if(owner)ownerMode();const name=owner?'OWNER | المالك':(data.fullName||user.displayName||'طالب شذرات'),username=owner?'OWNER | المالك':(data.username||`student_${user.uid.slice(0,6)}`);document.querySelector('[data-student-name]').textContent=name;document.querySelector('[data-student-username]').textContent=owner?'المالك الرئيسي لمنصة شذرات':`@${username}`;document.querySelector('[data-student-avatar]').textContent=owner?'O':(name.trim()[0]||'ط').toUpperCase();const values={fullName:name,username:owner?'OWNER | المالك':`@${username}`,email:user.email||data.email||'—',phone:data.phone|| (data.phoneLast4?`•••• ${data.phoneLast4}`:'غير مضاف'),location:data.location||data.country||'غير محدد',studyLevel:owner?'—':(data.studyLevel||'غير محدد')};for(const [key,val] of Object.entries(values)){const el=document.querySelector(`[data-profile-value="${key}"]`);if(el)el.textContent=esc(val)}if(owner)return;const fields=[name,user.email,data.location||data.country,data.studyLevel,data.username],complete=Math.round(fields.filter(Boolean).length/fields.length*100);const bar=document.querySelector('#profile-progress-bar'),label=document.querySelector('#profile-progress-value');if(bar)bar.style.width=`${complete}%`;if(label)label.textContent=`${complete}%`;});
