import { getApp, getApps, initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { collection, getDocs, getFirestore, query, where } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
import { scholarshipCatalog, mergeScholarships } from './scholarship-catalog.js';
if(location.pathname.endsWith('/scholarships.html')){
 const cards=document.querySelector('#scholarship-cards'),count=document.querySelector('#scholarship-count'),empty=document.querySelector('#scholarship-empty');
 const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const icon=c=>({'روسيا':'🇷🇺','المجر':'🇭🇺','تركيا':'🇹🇷'}[c]||'🌍');
 const date=v=>{if(!v)return null;const d=new Date(String(v).length===10?`${v}T00:00:00`:v);return isNaN(d)?null:d};
 const prettyDate=v=>{const d=date(v);return d?d.toLocaleDateString(document.documentElement.lang==='en'?'en-US':'ar-SA',{year:'numeric',month:'long',day:'numeric'}):(document.documentElement.lang==='en'?'Awaiting announcement':'بانتظار الإعلان')};
 const timer=s=>{const en=document.documentElement.lang==='en',now=Date.now(),o=date(s.openDate||s.openingDate),c=date(s.deadline||s.closeDate||s.endDate);let t,l;if(o&&now<o){t=o;l=en?'Applications open in':'يفتح التقديم خلال'}else if(c&&now<c){t=c;l=en?'Applications close in':'ينتهي التقديم خلال'}else if(c&&now>=c)return{l:en?'Application status':'حالة التقديم',v:en?'Closed':'مغلق حاليًا'};else return{l:en?'Application date':'موعد التقديم',v:s.statusLabel|| (en?'Awaiting announcement':'بانتظار الإعلان')};const total=Math.max(0,t-now),days=Math.floor(total/86400000),hours=Math.floor((total%86400000)/3600000),mins=Math.floor((total%3600000)/60000);let v;if(en){if(days>0)v=`${days}d${hours?` ${hours}h`:''}`;else if(hours>0)v=`${hours}h${mins?` ${mins}m`:''}`;else v=`${Math.max(1,mins)}m`}else{if(days>0)v=`${days} يوم${hours?` و ${hours} ساعة`:''}`;else if(hours>0)v=`${hours} ساعة${mins?` و ${mins} دقيقة`:''}`;else v=`${Math.max(1,mins)} دقيقة`}return{l,v}};
 let all=mergeScholarships([]).filter(x=>x.publishStatus==='published').sort((a,b)=>(a.sortOrder??999)-(b.sortOrder??999));let active='all';
 function text(s,key,fallback){return document.documentElement.lang==='en'?(s.en?.[key]||fallback):s[key]}
 function render(){const en=document.documentElement.lang==='en',items=active==='all'?all:all.filter(s=>s.country===active);if(count)count.textContent=en?`${items.length} scholarships`:`${items.length} منحة`;if(empty)empty.hidden=!!items.length;if(!cards)return;cards.innerHTML=items.map(s=>{const slug=s.slug||s.id,t=timer(s),levels=(s.studyLevels||[]).slice(0,4).join(' • '),stageCount=(s.stagesDetailed||[]).length;return `<article class="scholarship-card scholarship-${s.country==='روسيا'?'ru':s.country==='المجر'?'hu':s.country==='تركيا'?'tr':'global'}"><div class="scholarship-accent"></div><div class="scholarship-card-top"><span class="country-chip">${icon(s.country)} ${esc(en?(s.en?.country||s.country):s.country||'دولي')}</span><span class="status-chip">${esc(en?(s.en?.statusLabel||s.statusLabel):s.statusLabel||'منحة')}</span></div><div class="scholarship-provider">${esc(en?(s.en?.provider||s.provider):s.provider||'جهة مانحة')}</div><h2>${esc(en?(s.en?.title||s.title):s.title)}</h2><p class="scholarship-summary">${esc(en?(s.en?.shortDescription||s.shortDescription):s.shortDescription||'')}</p><div class="scholarship-countdown"><small>${esc(t.l)}</small><strong>${esc(t.v)}</strong><span>${en?'Opening date':'تاريخ البداية'}: ${esc(prettyDate(s.openDate||s.openingDate))}</span></div><div class="scholarship-meta-row"><div><small>${en?'Funding':'التمويل'}</small><b>${esc(en?(s.en?.funding||s.funding):s.funding|| (en?'By program':'حسب البرنامج'))}</b></div><div><small>${en?'Study levels':'المراحل الدراسية'}</small><b>${esc(levels|| (en?'By program':'حسب البرنامج'))}</b></div><div><small>${en?'Application stages':'مراحل التقديم'}</small><b>${stageCount?(en?`${stageCount} detailed stages`:`${stageCount} مراحل مفصلة`):(en?'See full guide':'تظهر داخل الدليل')}</b></div></div><a class="btn primary scholarship-details-btn" href="scholarship.html?slug=${encodeURIComponent(slug)}">${en?'View scholarship details':'عرض تفاصيل المنحة'}</a></article>`}).join('')}
 document.querySelectorAll('button.country-filter[data-country]').forEach(btn=>btn.onclick=e=>{e.preventDefault();e.stopPropagation();active=btn.dataset.country||'all';document.querySelectorAll('button.country-filter').forEach(x=>x.classList.toggle('is-active',x===btn));render();return false});
 // Fast path: paint verified local catalog immediately; no network wait.
 render();
 window.addEventListener('shazarat-language-change',render);
 // Background refresh: Firebase updates the already-visible list when available.
 requestAnimationFrame(async()=>{try{const app=getApps().length?getApp():initializeApp(firebaseConfig),db=getFirestore(app);const snap=await getDocs(query(collection(db,'scholarships'),where('publishStatus','==','published')));const remote=snap.docs.map(d=>({id:d.id,...d.data()}));if(remote.length){all=mergeScholarships(remote).filter(x=>x.publishStatus==='published').sort((a,b)=>(a.sortOrder??999)-(b.sortOrder??999));render()}}catch(e){console.warn('Scholarships background refresh skipped',e)}});
 setInterval(render,60000);
}
