import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{collection,getDocs,getFirestore,query,where}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import{firebaseConfig}from'./firebase-config.js';
import{mergeScholarships}from'./scholarship-catalog.js';
const root=document.querySelector('#scholarship-detail'),slug=new URLSearchParams(location.search).get('slug');
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(!slug){root.innerHTML='<div class="empty">لم يتم تحديد المنحة.</div>';throw new Error('missing slug')}
const app=getApps().length?getApp():initializeApp(firebaseConfig),db=getFirestore(app);let remote=[];try{const s=await getDocs(query(collection(db,'scholarships'),where('slug','==',slug)));remote=s.docs.map(d=>({id:d.id,...d.data()}))}catch(e){console.warn('remote scholarship unavailable',e)}
const item=mergeScholarships(remote).find(x=>(x.slug||x.id)===slug);if(!item){root.innerHTML='<div class="empty">لم نعثر على هذه المنحة.</div>'}else{document.title=`${item.title} | شذرات للمنح`;const facts=item.facts||[];root.innerHTML=`<article class="card scholarship-detail"><span class="tag">${esc(item.statusLabel||'راجع الحالة')}</span><h1>${esc(item.title)}</h1><p class="lead">${esc(item.shortDescription||'')}</p><div class="grid grid-3">${facts.map(f=>`<div class="stat"><small>${esc(f[0])}</small><b style="font-size:17px">${esc(f[1])}</b></div>`).join('')}</div><div class="grid grid-2" style="margin-top:20px"><section class="card"><h2>المراحل الدراسية</h2><p>${(item.studyLevels||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join(' ')||'حسب البرنامج'}</p><h2>التمويل</h2><p>${esc(item.funding||'حسب البرنامج')}</p></section><section class="card"><h2>المستندات المطلوبة</h2><ol>${(item.documents||[]).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>راجع المصدر الرسمي.</li>'}</ol></section></div><section class="card" style="margin-top:20px"><h2>خطوات التقديم</h2><ol>${(item.steps||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section><div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:20px">${item.officialUrl?`<a class="btn outline" href="${esc(item.officialUrl)}" target="_blank" rel="noopener">المصدر الرسمي ↗</a>`:''}${item.applyUrl?`<a class="btn primary" href="${esc(item.applyUrl)}" target="_blank" rel="noopener">التقديم الرسمي ↗</a>`:''}<a class="btn outline" href="community.html?scholarship=${encodeURIComponent(slug)}">مجتمع هذه المنحة</a></div></article>`}
