import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{collection,getDocs,getFirestore,query,where}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import{firebaseConfig}from'./firebase-config.js';import{mergeScholarships}from'./scholarship-catalog.js';
const root=document.querySelector('#scholarship-detail'),slug=new URLSearchParams(location.search).get('slug'),esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));if(!slug){root.innerHTML='<div class="empty">لم يتم تحديد المنحة.</div>';throw new Error('missing slug')}
const app=getApps().length?getApp():initializeApp(firebaseConfig),db=getFirestore(app);let remote=[];try{const s=await getDocs(query(collection(db,'scholarships'),where('slug','==',slug)));remote=s.docs.map(d=>({id:d.id,...d.data()}))}catch(e){console.warn(e)}
const item=mergeScholarships(remote).find(x=>(x.slug||x.id)===slug);
const list=(title,arr,cls='detail-panel')=>arr?.length?`<section class="${cls}"><h2>${title}</h2><ul class="doc-list">${arr.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:'';
function trackGroups(x){const lv=x.studyLevels||[],has=b=>lv.includes(b),groups=[];if(x.slug==='open-doors'){if(has('بكالوريوس')||has('ماجستير'))groups.push({id:'ba-ma',label:'البكالوريوس والماجستير',icon:'🎓',keys:['البكالوريوس','الماجستير']});if(has('دكتوراه'))groups.push({id:'phd',label:'الدكتوراه',icon:'📚',keys:['الدكتوراه']});if(has('ما بعد الدكتوراه'))groups.push({id:'postdoc',label:'ما بعد الدكتوراه',icon:'🔬',keys:['ما بعد الدكتوراه']});return groups}if(has('بكالوريوس')||has('ماجستير'))groups.push({id:'ba-ma',label:has('بكالوريوس')&&has('ماجستير')?'البكالوريوس والماجستير':has('بكالوريوس')?'البكالوريوس':'الماجستير',icon:'🎓',keys:['البكالوريوس','الماجستير'].filter(has)});if(has('دكتوراه'))groups.push({id:'phd',label:'الدكتوراه',icon:'📚',keys:['دكتوراه']});if(has('ما بعد الدكتوراه'))groups.push({id:'postdoc',label:'ما بعد الدكتوراه',icon:'🔬',keys:['ما بعد الدكتوراه']});if(!groups.length&&lv.length)groups.push({id:'all',label:lv.join(' و '),icon:'🎓',keys:lv});return groups}
function relevantEligibility(g,arr=[]){const specific=arr.filter(t=>g.keys.some(k=>String(t).includes(k)));const common=arr.filter(t=>!/البكالوريوس|الماجستير|الدكتوراه|ما بعد الدكتوراه/.test(String(t)));return [...common,...specific]}
function relevantStages(g,arr=[]){if(item.slug!=='open-doors')return arr;if(g.id==='ba-ma')return arr.filter(s=>!/الثالثة|ما بعد الدكتوراه/.test(s.title||''));if(g.id==='phd')return arr.filter(s=>!/ما بعد الدكتوراه/.test(s.title||''));if(g.id==='postdoc')return arr.map(s=>({...s,items:(s.items||[]).filter(v=>!/البكالوريوس|الماجستير/.test(v))})).filter(s=>!/اختبار مراقب/.test(s.title||'')||s.items.length);return arr}
if(!item){root.innerHTML='<div class="empty">لم نعثر على هذه المنحة.</div>'}else{document.title=`${item.title} | شذرات للمنح`;const groups=trackGroups(item),stages=item.stagesDetailed||[];root.innerHTML=`<div class="scholarship-detail-shell detail-theme-${item.country==='روسيا'?'ru':item.country==='المجر'?'hu':item.country==='تركيا'?'tr':'global'}"><section class="detail-hero-card"><div class="detail-badges"><span>${esc(item.country||'دولي')}</span><span>${esc(item.funding||'حسب البرنامج')}</span><span>${esc(item.statusLabel||'راجع الحالة')}</span></div><h1>${esc(item.title)}</h1><p class="lead">${esc(item.shortDescription||'')}</p><p><b>الجهة:</b> ${esc(item.provider||'—')}</p></section>${item.facts?.length?`<section class="detail-facts">${item.facts.map(f=>`<div class="detail-fact"><small>${esc(f[0])}</small><b>${esc(f[1])}</b></div>`).join('')}</section>`:''}${groups.length?`<section class="detail-panel track-switcher"><div class="section-title-row"><div><span class="mini-eyebrow">اختر مرحلتك الدراسية</span><h2>اعرض المعلومات التي تخصك فقط</h2></div><span class="switch-hint">اضغط للتبديل</span></div><div class="track-tabs">${groups.map((g,i)=>`<button type="button" class="track-tab${i===0?' active':''}" data-track="${g.id}"><span>${g.icon}</span>${esc(g.label)}</button>`).join('')}</div><div id="track-panel"></div></section>`:''}${item.subjectAreas?.length?`<section class="detail-panel interactive-panel"><button class="section-toggle" type="button" aria-expanded="true"><span><b>المجالات والتخصصات الرئيسية</b><small>${item.subjectAreas.length} مجال</small></span><i>⌄</i></button><div class="toggle-body open"><div class="subject-grid">${item.subjectAreas.map(x=>`<div class="subject-chip">${esc(x)}</div>`).join('')}</div><p class="muted">داخل كل مجال قد توجد برامج وتخصصات فرعية تختلف حسب المرحلة والجامعة.</p></div></section>`:''}${item.portfolio?.length?`<section class="detail-panel interactive-panel"><button class="section-toggle" type="button" aria-expanded="false"><span><b>البورتفوليو وما تحتاج لتجهيزه</b><small>${item.portfolio.length} عناصر</small></span><i>⌄</i></button><div class="toggle-body">${list('',item.portfolio,'inner-list')}</div></section>`:''}<div class="detail-grid">${list('المستندات المطلوبة',item.documents)}${list('ماذا يغطي التمويل؟',item.coverage)}</div>${list('ملاحظات مهمة قبل التقديم',item.notes)}<section class="detail-panel source-panel"><h2>المصدر الرسمي</h2><p>الموقع الرسمي وحساب المتقدم هما المرجع النهائي لأي تغيير.</p><div class="detail-actions">${item.officialUrl?`<a class="btn outline" href="${esc(item.officialUrl)}" target="_blank" rel="noopener">المصدر الرسمي ↗</a>`:''}${item.applyUrl?`<a class="btn primary" href="${esc(item.applyUrl)}" target="_blank" rel="noopener">التقديم الرسمي ↗</a>`:''}<a class="btn outline" href="community.html?scholarship=${encodeURIComponent(slug)}">مجتمع هذه المنحة</a><a class="btn outline" href="scholarships.html">العودة للمنح</a></div></section></div>`;
 const panel=root.querySelector('#track-panel');function drawTrack(g){const elig=relevantEligibility(g,item.eligibility||[]),sg=relevantStages(g,stages);panel.innerHTML=`<div class="track-content"><div class="track-summary"><span>${g.icon}</span><div><small>المسار المحدد</small><b>${esc(g.label)}</b></div></div>${elig.length?`<div class="track-block"><h3>من يستطيع التقديم؟</h3><ul>${elig.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${sg.length?`<div class="track-block"><h3>مراحل هذا المسار</h3><div class="stage-list detailed">${sg.map((s,i)=>`<article class="stage-item"><div><b>${esc(s.title||`المرحلة ${i+1}`)}</b>${s.date?`<small class="stage-date">${esc(s.date)}</small>`:''}<ul>${(s.items||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></article>`).join('')}</div></div>`:''}</div>`}
 if(groups.length){drawTrack(groups[0]);root.querySelectorAll('.track-tab').forEach(btn=>btn.onclick=()=>{root.querySelectorAll('.track-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');drawTrack(groups.find(g=>g.id===btn.dataset.track)||groups[0])})}
 root.querySelectorAll('.section-toggle').forEach(btn=>btn.onclick=()=>{const body=btn.parentElement.querySelector('.toggle-body'),open=!body.classList.contains('open');body.classList.toggle('open',open);btn.setAttribute('aria-expanded',String(open))})
}
