import { getApp, getApps, initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { collection, getDocs, getFirestore, query, where } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
import { mergeScholarships } from './scholarship-catalog.js';
if(location.pathname.endsWith('/scholarships.html')){
 const app=getApps().length?getApp():initializeApp(firebaseConfig),db=getFirestore(app),cards=document.querySelector('#scholarship-cards'),count=document.querySelector('#scholarship-count'),empty=document.querySelector('#scholarship-empty');
 const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const icon=c=>({'روسيا':'🇷🇺','المجر':'🇭🇺','تركيا':'🇹🇷'}[c]||'🌍');
 const date=v=>{if(!v)return null;const d=new Date(String(v).length===10?`${v}T00:00:00`:v);return isNaN(d)?null:d};
 const timer=s=>{const now=Date.now(),o=date(s.openDate||s.openingDate),c=date(s.deadline||s.closeDate||s.endDate);let t,l;if(o&&now<o){t=o;l='يفتح التقديم خلال'}else if(c&&now<c){t=c;l='ينتهي التقديم خلال'}else if(c&&now>=c)return{l:'حالة التقديم',v:'مغلق حاليًا'};else return{l:'موعد التقديم',v:s.statusLabel||'بانتظار الإعلان'};const mins=Math.max(0,Math.floor((t-now)/60000)),hours=Math.floor(mins/60),days=Math.floor(hours/24);return{l,v:days?`${days} يوم`:hours?`${hours} ساعة`:`${Math.max(1,mins)} دقيقة`}};
 let remote=[];try{const snap=await getDocs(query(collection(db,'scholarships'),where('publishStatus','==','published')));remote=snap.docs.map(d=>({id:d.id,...d.data()}))}catch(e){console.warn(e)}const all=mergeScholarships(remote).filter(x=>x.publishStatus==='published').sort((a,b)=>(a.sortOrder??999)-(b.sortOrder??999));let active='all';
 function render(){const items=active==='all'?all:all.filter(s=>s.country===active);if(count)count.textContent=`${items.length} منحة`;if(empty)empty.hidden=!!items.length;if(!cards)return;cards.innerHTML=items.map(s=>{const slug=s.slug||s.id,t=timer(s),levels=(s.studyLevels||[]).slice(0,2).join('، ');return `<article class="scholarship-card scholarship-${s.country==='روسيا'?'ru':s.country==='المجر'?'hu':s.country==='تركيا'?'tr':'global'}"><div class="scholarship-card-top"><span class="country-chip">${icon(s.country)} ${esc(s.country||'دولي')}</span><span class="status-chip">${esc(s.statusLabel||'منحة')}</span></div><div class="scholarship-provider">${esc(s.provider||'جهة مانحة')}</div><h2>${esc(s.title)}</h2><p class="scholarship-summary">${esc(s.shortDescription||'')}</p><div class="scholarship-quick-info"><div class="countdown-fact"><small>${esc(t.l)}</small><b>${esc(t.v)}</b></div><div><small>التمويل</small><b>${esc(s.funding||'حسب البرنامج')}</b></div>${levels?`<div><small>المراحل</small><b>${esc(levels)}</b></div>`:''}</div><a class="btn primary scholarship-details-btn" href="scholarship.html?slug=${encodeURIComponent(slug)}">عرض تفاصيل المنحة</a></article>`}).join('')}
 document.querySelectorAll('button.country-filter[data-country]').forEach(btn=>btn.onclick=e=>{e.preventDefault();e.stopPropagation();active=btn.dataset.country||'all';document.querySelectorAll('button.country-filter').forEach(x=>x.classList.toggle('is-active',x===btn));render();return false});render();setInterval(render,60000);
}
