import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{collection,doc,getDocs,getFirestore,query,updateDoc,where}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import{firebaseConfig}from'./firebase-config.js';
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),root=document.querySelector('#support-replies');const badges=[...document.querySelectorAll('[data-support-badge]')],dashboardCount=document.querySelector('[data-dashboard-support-count]');
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=s=>({new:'جديدة',waiting:'قيد المراجعة',replied:'تم الرد',closed:'مغلقة'})[s]||s||'جديدة',time=x=>x?.createdAt?.toMillis?.()||0;
async function load(user){if(!root)return;root.innerHTML='<div class="empty">جاري تحميل رسائلك…</div>';try{const snap=await getDocs(query(collection(db,'messages'),where('userId','==',user.uid)));const rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>time(b)-time(a));root.innerHTML=rows.length?rows.map(x=>`<article class="support-thread" data-message-id="${x.id}"><div class="support-head"><div><b>${esc(x.serviceTitle||x.type||'رسالة إلى الإدارة')}</b><small>${x.createdAt?.toDate?x.createdAt.toDate().toLocaleString('ar-SA'):'—'}</small></div><span class="tag">${esc(label(x.status))}</span></div><div class="support-message"><small>رسالتك</small><p>${esc(x.message||'')}</p></div>${x.adminReply?`<div class="support-reply"><small>رد الإدارة</small><p>${esc(x.adminReply)}</p><time>${x.repliedAt?.toDate?x.repliedAt.toDate().toLocaleString('ar-SA'):''}</time></div>`:'<div class="support-waiting">لم يصل رد من الإدارة بعد.</div>'}</article>`).join(''):'<div class="empty">لم ترسل أي رسالة إلى الإدارة حتى الآن.</div>'}catch(e){console.error(e);root.innerHTML='<div class="empty">تعذر تحميل الرسائل الآن. إذا استمرت المشكلة تواصل مع الإدارة.</div>'}}
async function unreadSupport(user){try{const snap=await getDocs(query(collection(db,'users',user.uid,'notifications'),where('type','==','support'))),unread=snap.docs.filter(d=>d.data().read===false);badges.forEach(badge=>{badge.textContent=String(unread.length);badge.hidden=!unread.length});if(dashboardCount)dashboardCount.textContent=String(unread.length);window.ShadratProfileDashboard?.setTask('support',unread.length?{priority:30,title:unread.length===1?'عندك رد جديد من الإدارة':`عندك ${unread.length} ردود جديدة من الإدارة`,text:'افتح ردود الإدارة وتأكد إذا كان مطلوب منك أي شيء.',label:'عرض الردود',tab:'support'}:null);return unread}catch(e){console.warn('support notification count failed',e);return null}}
async function markSupportNotificationsRead(user){try{const unread=await unreadSupport(user);if(!unread)return;await Promise.all(unread.map(d=>updateDoc(doc(db,'users',user.uid,'notifications',d.id),{read:true})));badges.forEach(badge=>badge.hidden=true);if(dashboardCount)dashboardCount.textContent='0';window.ShadratProfileDashboard?.setTask('support',null)}catch(e){console.warn('support notification read update failed',e)}}
onAuthStateChanged(auth,user=>{if(!user)return;load(user);unreadSupport(user);const tab=document.querySelector('[data-profile-tab="support"]');tab?.addEventListener('click',()=>markSupportNotificationsRead(user));});
