import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import{collection,doc,getDocs,getFirestore,orderBy,query,updateDoc,where}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import{firebaseConfig}from'./firebase-config.js';
const app=getApps().length?getApp():initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),root=document.querySelector('#support-replies');
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=s=>({new:'جديدة',waiting:'قيد المراجعة',replied:'تم الرد',closed:'مغلقة'})[s]||s||'جديدة';
async function load(user){if(!root)return;root.innerHTML='<div class="empty">جاري تحميل رسائلك…</div>';try{const snap=await getDocs(query(collection(db,'messages'),where('userId','==',user.uid),orderBy('createdAt','desc')));const rows=snap.docs.map(d=>({id:d.id,...d.data()}));root.innerHTML=rows.length?rows.map(x=>`<article class="support-thread" data-message-id="${x.id}"><div class="support-head"><div><b>${esc(x.serviceTitle||x.type||'رسالة إلى الإدارة')}</b><small>${x.createdAt?.toDate?x.createdAt.toDate().toLocaleString('ar-SA'):'—'}</small></div><span class="tag">${esc(label(x.status))}</span></div><div class="support-message"><small>رسالتك</small><p>${esc(x.message||'')}</p></div>${x.adminReply?`<div class="support-reply"><small>رد الإدارة</small><p>${esc(x.adminReply)}</p><time>${x.repliedAt?.toDate?x.repliedAt.toDate().toLocaleString('ar-SA'):''}</time></div>`:'<div class="support-waiting">لم يصل رد من الإدارة بعد.</div>'}</article>`).join(''):'<div class="empty">لم ترسل أي رسالة إلى الإدارة حتى الآن.</div>'}catch(e){console.error(e);root.innerHTML='<div class="empty">تعذر تحميل الرسائل الآن.</div>'}}
async function markSupportNotificationsRead(user){try{const snap=await getDocs(query(collection(db,'users',user.uid,'notifications'),where('type','==','support'),where('read','==',false)));await Promise.all(snap.docs.map(d=>updateDoc(doc(db,'users',user.uid,'notifications',d.id),{read:true})));}catch(e){console.warn('support notification read update failed',e)}}
onAuthStateChanged(auth,user=>{if(!user)return;load(user);const tab=document.querySelector('[data-profile-tab="support"]');tab?.addEventListener('click',()=>markSupportNotificationsRead(user),{once:true});});
