import{getApp,getApps,initializeApp}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import{doc,getDoc,getFirestore}from'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import{firebaseConfig}from'./firebase-config.js';
import{levelBadge}from'./level-badges.js?v=2';
import{levelFromXp,levelLabel}from'./level-system.js?v=3';
const PREF_PREFIX='shadrat-profile-v2:';
const app=getApps().length?getApp():initializeApp(firebaseConfig),db=getFirestore(app),root=document.querySelector('#public-profile'),uid=new URLSearchParams(location.search).get('uid');
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function prefsOf(profile={}){const raw=String(profile.avatarKey||'');if(!raw.startsWith(PREF_PREFIX))return{};try{return JSON.parse(raw.slice(PREF_PREFIX.length))||{}}catch{return{}}}
function avatarMarkup(profile={}){const prefs=prefsOf(profile),avatar=typeof prefs.avatarDataUrl==='string'&&prefs.avatarDataUrl.startsWith('data:image/')?prefs.avatarDataUrl:'',frame=/^(blue|glow|silver|gold|diamond|elite)$/.test(String(prefs.frame||''))?prefs.frame:'none',initial=esc((profile.fullName||profile.username||'ط').trim().slice(0,1).toUpperCase());return`<div class="public-avatar${frame!=='none'?` frame-${frame}`:''}">${avatar?`<img src="${esc(avatar)}" alt="الصورة الشخصية">`:initial}</div>`}
function chips(items,empty='لا يوجد شيء معروض حتى الآن.'){const arr=Array.isArray(items)?items.filter(Boolean).slice(0,16):[];return arr.length?`<div class="public-chip-list">${arr.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:`<p class="public-empty">${empty}</p>`}
if(!uid){root.innerHTML='<div class="notice">رابط الملف غير صحيح.</div>'}else{try{const snap=await getDoc(doc(db,'publicProfiles',uid));if(!snap.exists()||snap.data().visible!==true){root.innerHTML='<div class="notice">هذا الملف غير متاح للعامة.</div>'}else{const p=snap.data(),xp=Math.max(0,Number(p.xp)||0),level=Number(p.level)||levelFromXp(xp),label=levelLabel(level);root.innerHTML=`<div class="public-head">${avatarMarkup(p)}<div><div class="public-name"><div><h1 style="margin:0">${esc(p.fullName||'طالب شذرات')}</h1><p class="public-username">@${esc(p.username||'student')}</p></div>${levelBadge(level,34)}</div><p class="muted">${esc(p.studyLevel||'طالب في شذرات للمنح')}</p></div></div><div class="public-stats"><div class="public-stat"><b>Level ${label}</b><small>المستوى</small></div><div class="public-stat"><b>${xp.toLocaleString('ar')}</b><small>XP</small></div><div class="public-stat"><b>${Array.isArray(p.badges)?p.badges.length:0}</b><small>الشارات</small></div></div><section class="public-section"><h2>الإنجازات</h2>${chips(p.achievements,'لم يضف الطالب إنجازات عامة بعد.')}</section><section class="public-section"><h2>المهام التي أكملها</h2>${chips(p.completedTasks,'لا توجد مهام مكتملة معروضة بعد.')}</section><section class="public-section"><h2>الشارات</h2>${chips(p.badges,'لا توجد شارات إضافية معروضة.')}</section><p class="privacy-note">🔒 هذا ملف عام آمن. لا يظهر البريد أو رقم الجوال أو ملفات PDF/CV أو الطلبات أو الرسائل أو بيانات تسجيل الدخول أو أي مستندات خاصة.</p>`}}catch(e){console.error(e);root.innerHTML='<div class="notice">تعذر تحميل الملف الآن.</div>'}}
